### ISSUE TITLE
Iohook does not work with pkg package

### ISSUE THREAD

**Issue by Luke265** [wilix-team/iohook#100]
Iohook does not work with [pkg ](https://www.npmjs.com/package/pkg).

## Expected Behavior
When packed into a single executable, iohook should not throw `Module did not self-register.` error.

## Current Behavior
When starting executable which was created by [pkg ](https://www.npmjs.com/package/pkg), nodejs throws the following error
```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:729:18)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (\node_modules\**iohook\index.js:17**:21)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
```
If I rename the executable to `node.exe` and then run, it works just fine.

## Possible Solution
See: https://github.com/zeit/pkg/issues/161#issuecomment-413189708

## Steps to Reproduce (for bugs)
1. Install `pkg` and `iohook`
2. Create `index.js` file and put `require('iohook')`;
3. Run "pkg index.js"
4. Run executable

## Your Environment
**OS:** Windows
**NodeJS:** v10.9.0
**Iohook:** v0.2.0

**Comment by Djiit** [comment]
is there another solution than renaming the executable "node.exe" ? Because this solution is more a pkg-related problem than a iohook-related one.

**Comment by Luke265** [comment]
@Djiit I'm looking for other solutions, but nothing so far. I'm using multiple native modules, but only `iohook` is throwing that error.

**Comment by audstanley** [comment]
It actually works for me.  I added the iohook.node file to the same folder as the compiled biniary, and the binary runs just fine. This worked for me on Linux Mint 19.

**Comment by tbs-arpit** [comment]
@audstanley, Tried the same in windows no luck. Is there any files you changed to accomplish this?

**Comment by audstanley** [comment]
look for: ./node_modules/iohook/somwhereBinMaybe/iohook.node

That goes into the same folder as your binary... I just copy pasted, and it worked.

**Comment by Djiit** [comment]
Hi @Luke265 , did you sort it out ? I'm closing this but feel free to poke us if you need further help.

**Comment by Luke265** [comment]
Hi @Djiit, It was actually `pkg` module problem. I'm just going to leave a link here to pkg issue. There are multiple solutions written in the comments: https://github.com/zeit/pkg/issues/161
