### ISSUE TITLE
Bug: CAPS_LOCK is not be captured, and keyCodes of LEFT_META / RIGHT_META / RIGHT_ALT / UP / DOWN / LEFT / RIGHT are wrong

### ISSUE THREAD

**Issue by imcuttle** [wilix-team/iohook#104]
Bug: CAPS_LOCK is not be captured, and keyCodes of LEFT_META / RIGHT_META / RIGHT_ALT / UP / DOWN / LEFT / RIGHT are wrong

## Expected Behavior

- CAPS_LOCK should be captured with keyCode `58`
- LEFT_META: `125` / RIGHT_META: `126` / RIGHT_ALT: `100` / UP: `103` / DOWN: `108` / LEFT: `105` / RIGHT: `106`

## Current Behavior

- CAPS_LOCK is not be captured
- LEFT_META: `3675` / RIGHT_META: `3676` / RIGHT_ALT: `3640` / UP: `57416` / DOWN: `57424` / LEFT: `57419` / RIGHT: `57421`

## Steps to Reproduce (for bugs)

```javascript
const ioHook = require('iohook')
ioHook.start()
ioHook.on('keydown', console.log)
```

## Your Environment

* Version used: `iohook@0.2.0`
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs `v9.2.0`
* Operating System and version (desktop or mobile): macOS Sierra 10.12.6
* Link to your project: https://github.com/imcuttle/input-anywhere/blob/master/src/lib/getInputAnywhere.js

**Comment by Djiit** [comment]
Indeed this is directly linked to libuiohook not capturing CAPS_LOCK.
About the keycode, iohook doesn't use a native keymap (see #74 )
Sorry, closing this for now.
