### ISSUE TITLE
macOS: Accessibility feature required

### ISSUE THREAD

**Issue by alexgreenland** [wilix-team/iohook#107]
Hi,

Is there a way that we can use iohook without requiring the user to enable accessibility features? We don't want control and it looks like this library doesn't provide input control, we just want events. We've come from the osx-mouse library which didn't require accessibility features.

![image](https://user-images.githubusercontent.com/2202625/47607726-82e7c680-da1b-11e8-9613-cca6c6dd7da8.png)

**Comment by Djiit** [comment]
Hi Alex,

Unfortunately I'm not aware of such a feature. You'll have to ask permission to your user the first time (only) they launch your app. What you can do is making that a complete feature in your app : display a screenshot explaining why and how to do i, and so on...

**Comment by Djiit** [comment]
I'm closing this for now. Feel free to continue the discussion here and I'll be happy to reopen it.

**Comment by peernohell** [comment]
Hi,
We get this popup in development every time we start the electron app. So every time we want to restart electron we have this popup despite we change preferences to accept our electron app. Is that normal too?

**Comment by coalabear1010** [comment]
Is it impossible to grant access on electron.js for mac?

**Comment by coalabear1010** [comment]
The upwork time tracker app is also electron.js app.

**Comment by coalabear1010** [comment]
But it doesn't need the grant access

**Comment by WilixLead** [comment]
It may be related to signed app from apple. So you can publish app to App Store and sign it, after apple review users can download and use it.
I not shure about this case, may be you need request additional permissions from apple. 
Try ask about it in apple developer forum.

PS. If you don't want see popups when you working on code just go to Settings -> Security -> Universal access and click to Electron (or YOUR_APP_NAME) checkbox

Another way. Just run it as root (with sudo)

**Comment by Djiit** [comment]
Hi there, just reopening this for now.

**Comment by coalabear1010** [comment]
Can you fix this problem in further version?

**Comment by CarlosEduR** [comment]
Did anybody here have success doing so?
I'd like to know if it's possible to get events without asking for permission.

**Comment by jbagaresgaray** [comment]
Any news on this issue... Has anyone fixed this?

**Comment by CarlosEduR** [comment]
After some research, I figure out some people with the same problem. On the post, someone said when you authorize application over App Store, this pop-up stop showing up. But i'm not sure about it, I've not test.

**Comment by jbagaresgaray** [comment]
@CarlosEduR ... I tested it now with the app is code signed and no luck it still shows the accessibility popup...

**Comment by jbagaresgaray** [comment]
@CarlosEduR UPDATE: still fails to hide the accessibility prompt even the app is Code Signed and Notarize...

**Comment by ash0x0** [comment]
You should probably add this in your entitlements to avoid the annoying popup appearing all the time. When properly added to your entitlements it should only appear once, whether in development or production.
