### ISSUE TITLE
Fatal JS Error after packaging with electron

### ISSUE THREAD

**Issue by aizaku** [wilix-team/iohook#122]
The following error happens after packaging and running my app that uses iohook for win32-ia32 and win32-x64 (error messages are almost the same):
![image](https://user-images.githubusercontent.com/14979409/48149849-daacea00-e2c5-11e8-8a14-eac3585bdc47.png)

My OS Win10 x64
package.json includes:
```
"devDependencies": {
    "electron": "^3.0.4",
    "electron-packager": "^12.2.0",
    "electron-rebuild": "^1.8.2"
  },
  "dependencies": {
    "iohook": "^0.2.4"
  },
  "iohook": {
    "targets": [
      "node-64",
      "electron-64"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
```

code that is in the app related to iohook:
```
const ioHook = require('iohook');
ioHook.on('keydown', event => {
  console.log(event); //
});
ioHook.start();
```

**Comment by Djiit** [comment]
Hi ! Thanks for your ticket precision, I appreciate this.

Does the file listed in the last message exists on your file system ?

**Comment by aizaku** [comment]
Indeed it does 
![image](https://user-images.githubusercontent.com/14979409/48222743-ff749080-e39d-11e8-9075-b17029011ccb.png)

**Comment by aizaku** [comment]
Any news @Djiit ? At least a temporary workaround ?

**Comment by azertys** [comment]
I'm getting mostly the same problem, I think. When packed with electron 3, I'm getting:

```
  dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    Referenced from: /var/www/html/node_modules/segfault-handler/build/Release/segfault-handler.node
    Expected in: flat namespace

  dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    Referenced from: /var/www/html/node_modules/segfault-handler/build/Release/segfault-handler.node
    Expected in: flat namespace
```

The problem seems to be in the segfault handler package. If i comment that out, it works.

@aizaku As a workround, for me it works to remove the segfault handler from this package or downgrading to electron 2 also works.

**Comment by Djiit** [comment]
Hey @azertys , I just published version 0.3.0 *without* the segfault-handler dependency.

**Comment by azertys** [comment]
@Djiit Awesome, thanks. It works great now.

**Comment by tetreault** [comment]
this error still occurs with v0.3.0 on our end just fyi

**Comment by tetreault** [comment]
iohook works for us if we use electron v3
