### ISSUE TITLE
Question: What is your release build setup?

### ISSUE THREAD

**Issue by anoadragon453** [wilix-team/iohook#126]
Apologies for using the bug tracker for this, but our team wants to put iohook into production and we want to build iohook ourselves instead of using the precompiled binaries.

Could you clue us in to how you go about building for release? Do you manage to do so on a single system or do you employ chroot/VMs?

**Comment by Djiit** [comment]
You should be able to produce different builds for different platforms, especially since iohook has prebuilt binaries available. Are you using Electron ? If yes, check https://www.electron.build/multi-platform-build

**Comment by ash0x0** [comment]
Closing as stale and irrelevant.
