### ISSUE TITLE
"Failed to create apple event port" on Mac OS

### ISSUE THREAD

**Issue by jimmyhmiller** [wilix-team/iohook#129]
## Expected Behavior
Example code runs and prints mouse movements

## Current Behavior
Errors with "Failed to create apple event port. (0X41)"

```bash
❯ node hook.js 
hook_run [1121]: Accessibility API is enabled.
hook_run [1321]: Failed to create event port!
hook_run [1344]: Something, something, something, complete.
hook_enable [257]: Thread Result: (0X41).
Failed to create apple event port. (0X41)
```

`hook.js`
```javascript
const ioHook = require('iohook');

ioHook.on('mousemove', event => {
  console.log(event);
});

ioHook.start(true);
```

## Context
Not sure if this is a permissions issue. I saw a similar error about accessibility, but you can see that the Accessibility API is enabled. I tried `sudo` to no avail.

## Your Environment

* Version used: 0.2.5
* Environment name and version: node 10.0.0 
* Operating System and version: Mac OS Mojave (10.14.1)

**Comment by Djiit** [comment]
Hi @jimmyhmiller , I'm closing this issue because we didn't from you for a while; feel free to reopen it if you need further help.

**Comment by jimmyhmiller** [comment]
I understand closing old issues. But you didn't hear from me because there was never a response to the issue.

In case anyone else has this error, I never did figure out what was wrong. I just gave up on using the library.

**Comment by Djiit** [comment]
Hey, thanks for taking the time to answer anyway. I'm sorry we couldn't help you at this time -- I never stumbled upon this particular error.
