### ISSUE TITLE
Failed install on Windows 10 / Node 11.4.0

### ISSUE THREAD

**Issue by frankhale** [wilix-team/iohook#130]
## Expected Behavior

`npm i iohooks --save` installs successfully on Windows 10 using Node 11.4.0

## Current Behavior

The installation errors out with the following error:

`Prebuild for current platform (iohook-v0.2.5-node-v67-win32-x64) not found!`

## Possible Solution

Instead of failing on not finding a pre-built package allow the the building of the module. I know this is tricky on Windows but I have a full build setup with Visual Studio, etc... 

## Steps to Reproduce (for bugs)

Install Node 11.x
run `npm i iohooks` in your project and it will fail to install

## Your Environment

* Version used: 0.2.5
* Environment name and version Windows 10, Node 11.4.0
* Operating System and version (desktop or mobile): Desktop

**Comment by Djiit** [comment]
This should be ok with v0.2.6. Could you please try ?

Thanks

**Comment by frankhale** [comment]
Yep thank you, I will give it a try!

**Comment by frankhale** [comment]
Yep it's working with Node 11.4.0 x64, thank you!
