### ISSUE TITLE
TypeError: shortcut.releaseCallback is not a function

### ISSUE THREAD

**Issue by frankhale** [wilix-team/iohook#131]
iohook-0.2.6
Windows 10 x64
Node 11.4.0 x64

Given the following code example:

```javascript
const ioHook = require("iohook");

ioHook.start();

ioHook.registerShortcut([29, 56, 59], keys => {
  console.log("CTRL+ALT+F1 Pressed...");
});
```

results in:

```
D:\DEV\iohook-test>node index.js
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 1 layouts.
refresh_locale_list [493]: Received 1 locales.
load_input_helper [866]: refresh_locale_list() found 1 locale(s).
CTRL+ALT+F1 Pressed...
D:\DEV\iohook-test\node_modules\iohook\index.js:386
          shortcut.releaseCallback(keysTmpArray);
                   ^

TypeError: shortcut.releaseCallback is not a function
    at activatedShortcuts.forEach.shortcut (D:\DEV\iohook-test\node_modules\iohook\index.js:386:20)
    at Array.forEach (<anonymous>)
    at IOHook._handleShortcut (D:\DEV\iohook-test\node_modules\iohook\index.js:368:31)
    at IOHook._handler (D:\DEV\iohook-test\node_modules\iohook\index.js:221:14)
```

Additionally what keycodes are you using because when I look up keycodes I don't see these numbers. I see different numbers for CTRL+ALT+F1 (for instance F1 is keycode 112). I'm confused.

**Comment by frankhale** [comment]
So answering my question about where are your key codes coming from (because they are different from what you can look up online) I noticed that you are using an index into an array in the following file:

`https://github.com/wilix-team/iohook/blob/master/libuiohook/src/windows/input_helper.c`

Line 36 is where the array starts. I think this should be put into the docs because I was definitely stumped at how the keycodes were working.

**Comment by frankhale** [comment]
Okay line 386 of index.js needs a check to see if there was a valid callback in order to call. The docs don't talk about providing a release callback but hey I felt lucky so tried this and it worked

```javascript
ioHook.registerShortcut(
  [29, 56, 59],
  keys => {
    console.log("CTRL+ALT+F1 Pressed...");
  },
  () => {
    console.log("CTRL+ALT+F1 Released...");
  }
);
```

**Comment by Djiit** [comment]
Hello there !

Thanks for your feedback. Do you want to make a PR about this ? You could edit the docs as you need and propose your changes here - same thing for the callback check ;)

Cheers

**Comment by MadLittleMods** [comment]
I can also reproduce the error,

 - `iohook@0.3.0`
 - Windows 10
 - Node.js v10.12.0

```js
const iohook = require('iohook');

iohook.start();

// m shortcut
iohook.registerShortcut([50], () => {
   console.log('shortcut triggered');
});
```

```
node_modules\iohook\index.js:380
          shortcut.releaseCallback(keysTmpArray);
                   ^

TypeError: shortcut.releaseCallback is not a function
    at activatedShortcuts.forEach.shortcut (node_modules\iohook\index.js:380:20)
    at Array.forEach (<anonymous>)
    at IOHook._handleShortcut (node_modules\iohook\index.js:362:31)
    at IOHook._handler (node_modules\iohook\index.js:215:14)
```

**Comment by MadLittleMods** [comment]
I created a PR to fix this up https://github.com/wilix-team/iohook/pull/136

In the meantime, you can get around this by providing a 3rd argument, `releaseCallback`

```js
const iohook = require('iohook');

iohook.start();

// m shortcut
iohook.registerShortcut(
  [50], () => {
    console.log('shortcut triggered');
  },
  () => {}
);
```
