### ISSUE TITLE
How to differentiate between two keyboards

### ISSUE THREAD

**Issue by AlexZhouAA** [wilix-team/iohook#138]
I have two keyboards attaches to my Windows 7 computer.
Is it possible to know which keyboard sends the input when a keyboard event triggers.

I really need this function in my project.
Can anyone help me out with this.
Thanks a lot

**Comment by robatwilliams** [comment]
Duplicate of #103 ?

**Comment by Djiit** [comment]
Goo catch @robatwilliams , closing this one in favor of #103
