### ISSUE TITLE
Any plan for magic mouse gesture support? 

### ISSUE THREAD

**Issue by CColon1** [wilix-team/iohook#142]
Any plan for magic mouse gesture support?

**Comment by Djiit** [comment]
Hi there! Maybe @WilixLead has some thoughts about it ?

**Comment by ash0x0** [comment]
Probably not. If they just so happen to be normal HID keycodes then sure, will probably be captured. Otherwise, nope. Anyways, if anyone is interested in this reopen but do take the PR :)
