### ISSUE TITLE
Electron 4 support?

### ISSUE THREAD

**Issue by anhang** [wilix-team/iohook#144]
Any chance we can get electron 4 (electron-v69) support?

**Comment by kolnogorov** [comment]
I agree, now it doesn't work with actual Electron/Node.js versions at all.
What should we do, downgrade Electron or there are any better ways to get it to work?

**Comment by Djiit** [comment]
Hi there, I did try to make prebuilt binaries for electron 4 but I hit some bugs.
I'll try to find some time to re-test it.
However the build is the same as describe in the docs

**Comment by Djiit** [comment]
Nope, it's clearly out of my knowledge.
I Did some tests on travis : just adding the new target (electron 4.0.5, abi 69) got me an error :   

```
[ 87%] Building CXX object CMakeFiles/iohook.dir/src/iohook.cc.o
In file included from /home/travis/build/wilix-team/iohook/src/iohook.h:3:0,
                 from /home/travis/build/wilix-team/iohook/src/iohook.cc:1:
/home/travis/build/wilix-team/iohook/node_modules/nan/nan.h:24:26: fatal error: node_version.h: No such file or directory
 #include <node_version.h>
```

Any C++ dev here ?

**Comment by Djiit** [comment]
@DCzajkowski can you help us here ? thanks !

**Comment by anoadragon453** [comment]
Well I've tried messing about with this for about 2 hours and haven't figured out a fix. I tried switching all the dependencies to nan `v2.12.1` but that hasn't solved it (we've had nan troubles in the past, but seems to just be a red herring).

Search engines don't bring much luck.

Darn you `node_version.h`!

**Comment by anoadragon453** [comment]
Some insight: https://github.com/electron/electron/issues/17072#issuecomment-465692213

**Comment by Djiit** [comment]
Good catch. The problem here is you will need a c++11 compiler to use
cmakejs 4.x or 5.x (5.1 is the latest) but iohook still use a lot of c++99
code. Do you want to have a look? You can start by bumping cmakejs and look
into the flags used in cmakelist.txt

--
Julien

Le mer. 20 févr. 2019 à 19:14, Andrew Morgan <notifications@github.com> a
écrit :

**Comment by anoadragon453** [comment]
Is c++11 not backwards compatible with c++99? I can start with what you've said. I really wanna get this working on Electron v4 for inclusion into https://github.com/vector-im/riot-web :D

**Comment by anoadragon453** [comment]
So bumping `cmake-js` to `"^5.1.0"` seems to make it all just work???

**Comment by Djiit** [comment]
This is not what I saw ahah. Can you make a PR with your code and see if
the CI passes ?

--
Julien

Le jeu. 21 févr. 2019 à 18:07, Andrew Morgan <notifications@github.com> a
écrit :

**Comment by anoadragon453** [comment]
#148

**Comment by kolnogorov** [comment]
I've tried to bump cmake to ^5.1.0 and build, but got the following error:

```
> iohook@0.3.1 build /Users/lovebeam/iohook
> cmake-js compile

[ '/usr/local/Cellar/node/11.5.0/bin/node',
  '/Users/lovebeam/iohook/node_modules/.bin/cmake-js',
  'compile' ]
info TOOL Using Unix Makefiles generator.
info CMD BUILD
info RUN cmake --build "/Users/lovebeam/iohook/build" --config Release
make: *** No targets specified and no makefile found.  Stop.
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "/Users/lovebeam/iohook/build"
info CMD CONFIGURE
info RUN cmake "/Users/lovebeam/iohook" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="5.1.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/Users/lovebeam/iohook/build/Release" -DCMAKE_JS_INC="/Users/lovebeam/.cmake-js/node-x64/v11.5.0/include/node;/Users/lovebeam/iohook/node_modules/nan" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="11.5.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION" -DCMAKE_SHARED_LINKER_FLAGS="-undefined dynamic_lookup"
Not searching for unused variables given on the command line.
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:53 (add_library):
  No SOURCES given to target: uiohook


-- Build files have been written to: /Users/lovebeam/iohook/build
ERR! OMG Process terminated: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.3.1 build: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iohook@0.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lovebeam/.npm/_logs/2019-03-05T20_44_38_046Z-debug.log
```

Well, atleast it started to build.

**Comment by DCzajkowski** [comment]
Hey @Djiit, sorry for being so late to the party. I would really like to help, but unfortunately I have no clue how. The only thing I can do is wish you good luck :)
