### ISSUE TITLE
Any demo?

### ISSUE THREAD

**Issue by fuzuyx** [wilix-team/iohook#146]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Djiit** [comment]
Hi there !

Would you like us to add a section about apps using iohook ? So you can have some real-world exampels ?

**Comment by Djiit** [comment]
Closing this, added an *Apps* section in the README.
