### ISSUE TITLE
Keyboard events not firing in Electron window

### ISSUE THREAD

**Issue by anhang** [wilix-team/iohook#147]
## Expected Behavior
When my selected window is an Electron window (or the detached Chrome debugger window), IoHook does not send any keyboard events.

## Current Behavior
Demo repo: https://github.com/visorgg/helloworld-electron
Download code, and just run `yarn install && yarn dev`.
Now, whenever I press a key with any of the two electron windows highlighted, the console doesn't log my event. However, as soon as I select any other window, the console starts logging keyboard events.

I have tried various versions of iohook and electron (2 and 3), on two different Windows 10 machines, and I can repro this consistently.

## Your Environment
```
helloworld$ node -v
v10.5.0
helloworld$ npm -v
6.2.0
helloworld$ yarn -v
1.10.1
```
OS: Windows 10.0.17134 Build 17134
Arch: x64

**Comment by osipuk** [comment]
I did download the your source code and run it on my window os.
but it's working fine.
When my selected window is an Electron window (or the detached Chrome debugger window), IoHook does  send any keyboard events fine.

**Comment by Djiit** [comment]
Hi there,

II don't have a windows machine right now, but I'm running iohook in a production app on Windows without any problems.

**Comment by anhang** [comment]
hm, that is very odd. I wonder if I have something installed locally on my machine that's conflicting with ioHook. Is there any known conflicts?

**Comment by Djiit** [comment]
Other use of libuiohook can interfere with iohook. But this is quite rare.
Can you try on another platform with the same code ? I won't have access to
a computer soon so I can't do it myself.

--
Julien

Le jeu. 21 févr. 2019 à 19:05, Anhang Zhu <notifications@github.com> a
écrit :

**Comment by anhang** [comment]
Ah I see what is going on. I do have local code that conflicts with libuiohook. Thanks!

**Comment by Rydez** [comment]
@anhang you wouldn't happen to remember what it was, would you? I'm struggling with this same issue.
