### ISSUE TITLE
Calling alert() breaks the app

### ISSUE THREAD

**Issue by Maidomax** [wilix-team/iohook#152]
On the "front-end" of my Electron app I call `alert()` to display a message to the user. This works fine before requiring iohook.

## Expected Behavior
I would expect tht including iohook doesn't make a difference with respect to this feature.

## Current Behavior
After requiring iohook with the sample code, when an alert is to be displayed, I only see a blank alert box appearing and then the entire app crashes without any feedback. Up until the point in which the alert is to be displayed, iohook works fine and tracks the mouse movements properly.

## Steps to Reproduce (for bugs)
1. Add `iohook` to your Electron project with the sample code
2. Build all dependencies as needed
3. Create a button in an electron window that triggers an `alert()`
4. Start the app, console will log the mouse movements, press the button, app crashes

## Your Environment
* Version used:
```
"electron": "^4.0.4",
"iohook": "^0.4.0",
```
* OS: Ubuntu Linux 18.04.2 LTS

**Comment by Djiit** [comment]
Hi there, I can't reproduce it here. Could you please provide us a small reproductible example, maybe in a github repository so we can investigate it further ? Thanks !
