### ISSUE TITLE
NodeJS: Error: Module did not self-register.

### ISSUE THREAD

**Issue by Romans96** [wilix-team/iohook#154]
Hello! I'm trying to build a NodeJS App with Nexe.

## Expected Behavior
Launching the app from console with `node index.js` works perfectly.

## Current Behavior
If i made it with nexe (or pkg), like `nexe index.js`.
It creates the .exe but launching it from console with .\test.exe, gives this error:
```
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 1 layouts.
refresh_locale_list [493]: Received 1 locales.
load_input_helper [866]: refresh_locale_list() found 1 locale(s).
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Mattia\Desktop\Autoit\testRobotJS\node_modules\iohook\index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

## Possible Solution
No idea on how to solve

## Steps to Reproduce (for bugs)
1 Create index.js, and package.json.
2 Install Nexe globally (removing typescript glbally)
3 install typescript locally in the app
4 install iohook
5 create an executable file with `nexe index.js`

## Context
I'm trying to build an executable

## Your Environment
NodeJS : 10.15.3
NPM: 6.9.0
iohook: 0.4.0
typescript: 3.3.4000
nexe:  nexe 3.0.0-beta.15

**Comment by Djiit** [comment]
Are you on Windows ?

**Comment by Romans96** [comment]
Yes i'm coding on windows, but i will host the app in a Linux VPS

Il giorno ven 29 mar 2019 alle ore 10:40 Julien Tanay <
notifications@github.com> ha scritto:

**Comment by Djiit** [comment]
Hi @Romans96 could you try with 0.4.6 ?

**Comment by zxc23** [comment]
Anyone having this problem with electron - I fixed it with electron-rebuild.

**Comment by Djiit** [comment]
Hey @Romans96, any news ? Can we close this one ?

**Comment by Djiit** [comment]
Closing this one because of lack of information. Feel free to ping me here if you want to reopen it with more details.

**Comment by korobaka** [comment]
@Djiit hi!
this is going on with version 0.9.3.
my code:
```
const ioHook = require('iohook');
let keystrokes = "Keystrokes start now : ";
ioHook.on("keydown", event => {
    keystrokes+= String.fromCharCode(event.rawcode);
});
ioHook.start();
```

the result:
```
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 6 layouts.
refresh_locale_list [493]: Received 6 locales.
load_input_helper [866]: refresh_locale_list() found 6 locale(s).
```

I tried to install 0.6.6 as recommended in #275, but this is not working (the installation process can't be done)
screenshot:

![image_2021-07-25_234416](https://user-images.githubusercontent.com/35098503/126914406-3e4b4a1a-f18c-4776-8d3b-160455780078.png)

any help would be welcome!
