### ISSUE TITLE
Electron: iohook Not Captured Any Events in Administrative windows. 

### ISSUE THREAD

**Issue by md-abbas** [wilix-team/iohook#156]
## Expected Behavior

I want to capture every mouse and keyboard event.
But it couldn't capture administration window.

## Current Behavior

**iohook Not capturing any events in admin windows. like command prompt , task manager, etc.,** 

## Your Environment

* Version used: iohook latest version
* Environment name and version : Electron 4.1.x and node 10.x.x
* Operating System and version (desktop or mobile): Desktop windows 10
* Link to your project: none

**Comment by Djiit** [comment]
Hi there, we're happy to help ! Could you please use our template so we can sort your issue out ?  Thanks

**Comment by md-abbas** [comment]
> 
> 
> Hi there, we're happy to help ! Could you please use our template so we can sort your issue out ? Thanks

Edited.. please check it now.

**Comment by karacas** [comment]
Try it by elevating your electron app, ms win block key/mouse listeners for protect apps with admin rights.

**Comment by md-abbas** [comment]
> 
> 
> Try it elevating your electron app, ms win block key/mouse listeners for protect apps with admin rights.

Thank you for your reply. But i don't have admin rights

**Comment by Djiit** [comment]
Oh, I see. I believe you need admin rights to interact with admin processes. I'm going to close this PR as this is not related to iohook.

**Comment by md-abbas** [comment]
> 
> 
> Oh, I see. I believe you need admin rights to interact with admin processes. I'm going to close this PR as this is not related to iohook.

Now i have Admin rights. but still not captured Taskmanager and cmd window.
