### ISSUE TITLE
iohook fails to require in electron/mswin/asar

### ISSUE THREAD

**Issue by karacas** [wilix-team/iohook#160]
For some reason it does not load uiohook.dll in electron/mswin/asar 
(modulePath resolve problem in: index.js / line 6).

Temporarily I could fixit whit this patch:
```
let pathIoHook = 'c:/test/node_modules/iohook/builds/electron-v69-win32-x64/build/Release/iohook.node';
let iohook = require('import-modify')('iohook', source => {
	return source.replace('require(modulePath)', 'require("' + pathIoHook + '")');
});
```

**Comment by Djiit** [comment]
Hi there ! We're happy to help but we need a bit more information. Could you please use the template we provide ? Thanks

**Comment by karacas** [comment]
I found the solution for this problem:
In windows ioHook modulePath file is `iohook.node`, but different from macos/linux windows needs an extra file: `uiohook.dll`.
asar decompress temporarament `iohook.node` in `%TEMP%`, but the file `uiohook.dll` isnt here and this causes fail.

### Solution:
Just copy `node_modules/iohook/builds/electron-v69-win32-x64/build/Release\uiohook.dll` 
to 
`%TEMP%` aka `(c:\Windows\Temp\)`

**Comment by chad187** [comment]
> I found the solution for this problem:
> In windows ioHook modulePath file is `iohook.node`, but different from macos/linux windows needs an extra file: `uiohook.dll`.
> asar decompress temporarament `iohook.node` in `%TEMP%`, but the file `uiohook.dll` isnt here and this causes fail.
> 
> ### Solution:
> Just copy `node_modules/iohook/builds/electron-v69-win32-x64/build/Release/uiohook.dll`
> to
> `%TEMP%` aka `(c:/Windows/Temp/)`

I believe you want me to copy uiohook.dll into c:/windows/temp/ this might fix the problem for my computer but how can I fix it programatically for all windows users? Obviously, I won't be able to manually copy that file over for each user

**Comment by karacas** [comment]
@chad187 

yes, you can make an script, ej:

``` js
const extract_uiohook_dll = () => {
   if (!isWin) return;

   const isRunningInAsar = require('electron-util').is.usingAsar;
   if (!isRunningInAsar) return false;

   const APP_ASAR_TMP = './out/app-win32-x64/resources/app.asar';
   const UIOHOOK_PATH = 'node_modules\\iohook\\builds\\electron-v70-win32-x64\\build\\Release\\uiohook.dll';

   const fs = require('fs');

   const iohookNodefilePath = normalicePath('%TEMP%' + '/uiohook.dll', true);
   if (fs.existsSync(iohookNodefilePath)) return;

   const asar = require('asar');
   const { app } = require('electron');
   const appAsar = isRunningInAsar ? String(app.getAppPath()) : APP_ASAR_TMP;
   let fileiohook = null;

   if (!fs.existsSync(appAsar)) {
      Logger.warn('fail make dll / not found', appAsar);
      return false;
   }

   try {
      fileiohook = asar.extractFile(appAsar, UIOHOOK_PATH);
      if (!fileiohook) return false;
      fs.writeFileSync(iohookNodefilePath, fileiohook);
      return true;
   } catch (e) {
      Logger.warn('fail make dll / extract', e, iohookNodefilePath);
      return false;
   }
};
```
