### ISSUE TITLE
iohook.node is not a valid Win32 application 

### ISSUE THREAD

**Issue by mlisakov** [wilix-team/iohook#161]
iohook v0.4.0(or 0.4.2) does not work on Windows 7 32-bit(node 8.15.1, electron 3.1.0)
Error: iohook.node is not a valid Win32 application 

I got iohook source code from https://github.com/wilix-team/iohook and create prebuild files for ABI 64 for win 32 ia32 targets using this
"supportedTargets": [
    [
      "electron",
      "3.0.0",
      "64"
    ],
    [
      "node",
      "10.0.0",
      "64"
    ]
  ]
Done this on Windows 32-bit OS
Then changed files in ..\node_modules\iohook\builds\iohook-v0.4.0-node-v64-win32-ia32\build\Release and  ..\node_modules\iohook\builds\iohook-v0.4.0-electron-v64-win32-ia32\build\Release with files i have created above
It fixed my problem

## Expected Behavior
Should download correct prebuild files from https://github.com/WilixLead/iohook/releases/download and works well

## Current Behavior
iohook v0.4.0(or 0.4.2) does not work on Windows 7 32-bit(node 8.15.1 electron 3.1.0)
Error: iohook.node is not a valid Win32 application 

## Possible Solution
update files
-iohook-v0.4.0-node-v64-win32-ia32.tar.gz
-iohook-v0.4.0-electron-v64-win32-ia32.tar.gz
here https://github.com/wilix-team/iohook/releases/tag/v0.4.0b
@matthewshirley  could you please take a look on iohook windows 32-bit problem

## Your Environment
Windows 7 32-bit
Node v8.15.1
Electron v3.1.0
iohook v0.4.0 ( v0.4.2 )

**Comment by Djiit** [comment]
Hi there !

Could you please paste us your `iohook` settigns in your package.json ? it seems your are targeting node 10 but using node 8 (if I read your issue correctly).

**Comment by mlisakov** [comment]
Thank you for quick reply!
Sorry for my mistake, node v10.15.3 installed

**Comment by erosha96** [comment]
I have the same problem right now. Trying on Windows 10 32 bit.
```PS Z:\Mouse> node -v
v11.13.0
PS Z:\Mouse> node shit.js
internal/modules/cjs/loader.js:846
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\Z:\Mouse\node_modules\iohook\builds\node-v67-win32-ia32\build\Release\iohook.node is not a valid Win32 application.
\\?\Z:\Mouse\node_modules\iohook\builds\node-v67-win32-ia32\build\Release\iohook.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:846:18)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (Z:\Mouse\node_modules\iohook\index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)```

**Comment by Djiit** [comment]
We definetely have a problem with win32 prebuilt binaries. I'll look into it when I can. Seems related to our AppVeyor config not building for the correct arch.

**Comment by uuai** [comment]
node64位可使用    node32位就是iohook.node不是有效的Win32应用程序  报错      系统win7  64位是怎么回事？

**Comment by gloatoriginal** [comment]
Same issue, 
`Error: \\?\C:\Projects\AutoClick\AutoClick\AutoClick\node_modules\iohook\builds\node-v64-win32-ia32\build\Release\iohook.node is not a valid Win32 application.`
windows 10 64bit, I run 32bit nodejs for robotjs to work with.

**Comment by staticbass** [comment]
same for me 👆

**Comment by Djiit** [comment]
Closing this for #139
