### ISSUE TITLE
iohook not working on windows but works on linux

### ISSUE THREAD

**Issue by lemon07r** [wilix-team/iohook#164]
## Expected Behavior
To work in windows a NW.js windows app as a keydown event handler.

## Current Behavior
Works perfectly on Linux (Pop_os! 19.04), but won't work at all on windows. Tested my project by removing iohook and using the onkeypress event handler to isolate this issue; project works fine without iohook.

## Steps to Reproduce (for bugs)
https://github.com/lemon07r/WPMCounter
Clone project, npm install to add iohook, run it as a desktop app with NW.js

## Context
I'm trying to make a desktop word per minute counter app that sits somewhere in your display as a small overlay to show your WPM (UI is not finished yet). Since the onekeypress javascript event handler only works when the window is in focus this wasn't a valid option for me, I needed a system wide keypress or keydown event handler. iohook has worked perfectly for me and those needs in my development system (linux), but unfortunately does not work in any of the windows computers I've tried testing it on. 
PS I am pretty new to node.js and development in general so I apologize if I missed something. 

## Your Environment
* Version used: 0.4.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): NW.js SDK 0.38.1, Node.js 12.1.0, npm 6.9.0
* Operating System and version (desktop or mobile): Pop_os! 19.04 (working), Windows 10 x64 (tested on a desktop with Pro, laptop with Student, laptop with home, and desktop with home edition, unsure of what versions, did not work on any of these 4 windows machines)
* Link to your project: https://github.com/lemon07r/WPMCounter

**Comment by Djiit** [comment]
I'm not quite sure we are compatible with NW.js at the moment. If anybody can look into this, I'm pretty new to NW.

**Comment by lemon07r** [comment]
> I'm not quite sure we are compatible with NW.js at the moment. If anybody can look into this, I'm pretty new to NW.

I can't seem to get my program to work on windows for the life of me. I tried doing it with electron.js instead and it didnt work either. Can anyone take a look or give things a shot? I've been trying to fix this for months now.

**Comment by ash0x0** [comment]
Closing as irrelevant.
