### ISSUE TITLE
Running the application hangs up the system for a while.

### ISSUE THREAD

**Issue by SergeyBelikof** [wilix-team/iohook#168]
Running the application hangs up the system for a while.

## Expected Behavior
The system should not hang when starting the application.

## Current Behavior
Running the application hangs up the system for a while.
The mouse moves intermittently for a few seconds (5-10).
**See demo video here: https://www.anymeeting.com/774-849-262/E958D683864E3D**
_You can use any name and random email to watch video._

## Possible Solution
The problem is in loading IOHook module.
let iohook = require('iohook');
probably somewhere here -> https://github.com/wilix-team/iohook/blob/master/src/iohook.cc

## Steps to Reproduce (for bugs)
Here is my test repo: https://github.com/SergeyBelikof/test_usage_iohook
1. Download code
2. Run npm install
3. Run npm start

## Your Environment
System information: Operating System: Windows 10 Pro 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434) 
Node.js 10.2.0 
Chromium 66.0.3359.181 
Electron 3.1.4
iohook v0.4.0 ( v0.4.2 )

**Comment by Lennon925** [comment]
I found this bug too, If you open two applications which use iohook, the whole system hangs up.

**Comment by bryanberger** [comment]
funny enough when you run through the command line `electron .` it doesn't hang, but on a compiled app it does.

**Comment by jhlee8804** [comment]
+1

**Comment by ash0x0** [comment]
Closing as stale and apparently fixed. Can't repro with newer node, electron and iohook. Feel free to reopen if still an issue.
