### ISSUE TITLE
32 bit is not supported， because the win32-ia32 release file iohook.node and  uiohook.dll are still 64 bit

### ISSUE THREAD

**Issue by alex8088** [wilix-team/iohook#169]
32 bit is not supported， because the win32-ia32 release file iohook.node and uiohook.dll are still 64 bit

@Djiit ， @WilixLead 

cmake-js can configure [arch ](https://github.com/cmake-js/cmake-js#runtimes)

your project build.js file :
`let args = [
      'rebuild',
      '--runtime-version=' + version,
      '--target_arch=' + arch,
      '--runtime=' + runtime,
     '--arch=ia32'
    ];`

**Comment by Djiit** [comment]
Hi there ! Would you mind making a PR for this ?

**Comment by alex8088** [comment]
> Hi there ! Would you mind making a PR for this ?
I have made a PR for this

**Comment by Djiit** [comment]
Hi @alex8088 . I'll wait for the build to finish then I'll publish v0.4.6 !
