### ISSUE TITLE
Close or terminate handlers to iohook.on(event)

### ISSUE THREAD

**Issue by Suhail** [wilix-team/iohook#173]
Is there a simple way to close or terminate handlers created for events?

For example:

```
iohook.on('keydown', () => {});
```

How can I remove/terminate that handler so that it no longer gets events to it.

Is there a way to make use of removeEventListener?

**Comment by Suhail** [comment]
Solution: `iohook.removeListener('keydown', process_event);`

iohook is a subclass of EventEmitter.

**Comment by Djiit** [comment]
Will it be more explicit if we add a proper, documented method ?

**Comment by Suhail** [comment]
I think if you just write an example in the docs you’re fine. It’s pretty clean since you subclass EventEmitter.

**Comment by nitti87** [comment]
Since there is no example of this in the docs, would you please add an example here instead?

**Comment by pgupt** [comment]
This is not working for me.

**Comment by pgupt** [comment]
I am listening for alt + space key. First time it listens fine. Second time, even though I press just space. it gives me alt+space.

**Comment by lacymorrow** [comment]
I was able to get `iohook.off('mousedown', myfunction)` to work
