### ISSUE TITLE
Using touchpad on my Razer laptop gives mousewheel direction 0

### ISSUE THREAD

**Issue by Suhail** [wilix-team/iohook#174]
Hey there,

I am trying mousewheel capture on my laptop's touchpad and I get a direction of 0:

```
{ amount: 5,
  clicks: 1,
  direction: 3,
  rotation: 0,
  type: 'mousewheel',
  x: 609,
  y: 871 }
```

Is there any way to get a proper rotation?

Everything works fine if I use my physical mouse though.

I am using Windows 10 on a Razer Blade: https://www.razer.com/gaming-laptops/razer-blade

**Comment by Djiit** [comment]
Hi there,
I'll try to reproduce that tonight

**Comment by Suhail** [comment]
Just to be clear I use two fingers to do the scrolling (like a macbook)

**Comment by Suhail** [comment]
Any news?

**Comment by Suhail** [comment]
In input_hook.c:497, I was able to get touchpad support working by simplifying it with this patch:

```c++
bool down = (short)HIWORD(mshook->mouseData) < 0;
event.data.wheel.rotation = (down) ? 1 : -1;

// Set the direction based on what event was received.
event.data.wheel.direction = direction;
```

**Comment by Suhail** [comment]
Side note: I am noticing it does not work in certain situations with some windows. For example, it'll work in Chrome but not work in Explorer to capture the mousewheel movement w/ the touchpad.

**Comment by ash0x0** [comment]
Closing as stale. Can't reproduce this issue on my windows laptop. Feel free to reopen if still an issue.
