### ISSUE TITLE
[Linux] "mousedown" event of the left mouse button is only fired when the mousebutton is released

### ISSUE THREAD

**Issue by lazytyper** [wilix-team/iohook#175]
On Linux, for the left mouse button, the mousedown event is only fired when the button is being released.

For the right and middle mouse button, it works correctly.

**Comment by Djiit** [comment]
Hi there, we're happy to help ! Could you please use our template so we can try to figure it out ?

**Comment by Djiit** [comment]
Closing this one because of lack of information. Feel free to ping me here if you want to reopen it with more details.
