### ISSUE TITLE
iohook makes debugging in VSCode unusable under Windows

### ISSUE THREAD

**Issue by Suhail** [wilix-team/iohook#176]
- VSCode Version: 1.35.1
- OS Version: Windows_NT x64 10.0.17763

## Problem

For some reason when I run VSCode, attempt to debug something, and set a breakpoint and merely require() this addon in NodeJS: https://github.com/wilix-team/iohook there's considerable lag, the mouse becomes jittery, and my entire computer becomes nearly unusable until I stop debugging.

Does this issue occur when all extensions are disabled?: yes

**Comment by Djiit** [comment]
Hi there ! I don't have a Windows machine right now but I'll try to have a look at it this weekend.

**Comment by Suhail** [comment]
Ok. Let me know if you need a Windows machine.

**Comment by Djiit** [comment]
Hi there,

The good news is I can reproduce it adding a breakpoint in the `example/example.js` file : VScode completely freeze on my machine.

It seems that if I remove the `console.log` handler on the listener, VScode stays stable and I can debug the program.

Could you share with us a minimal reproducible example ?

**Comment by Suhail** [comment]
I'll try removing console.log's and seeing if it goes away. I'd still urge us to figure out root cause since while debugging you usually want to use console.log.

**Comment by Djiit** [comment]
You're right, I was referring to the multiple, simultaneous calls to
console.log.

Let me know if you can narrow down the problem.

--
Julien

**Comment by ash0x0** [comment]
Closing as fixed in #294
