### ISSUE TITLE
Bug: Iohook makes electron app draggable area contextmenu menu item can't be triggered and contextmenu can't be destroyed.

### ISSUE THREAD

**Issue by zerotung** [wilix-team/iohook#177]
## Expected Behavior
Iohook should not affect the system's performance on right-click in the draggable area of the window.

## Current Behavior
When right-click in the draggable area of the window it will evoke operate system's contextmenu, but I cannot reach to the menu item, and I can't close contextmenu when click outside.

## Steps to Reproduce (for bugs)
```javascript
// main.js
const { app, BrowserWindow } = require('electron')

let win

function createWindow () {

  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    },
    frame: false,
  })

  win.loadFile('index.html')

  win.webContents.openDevTools()

  const iohook = require('iohook');
  iohook.start();

  win.on('closed', () => {
    win = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <style>
      #appbar { -webkit-app-region: drag; height: 30px; background-color: bisque; }
    </style>
  </head>
  <body>
    <div id="appbar">sefa</div>
    <h1>Hello World!</h1>
    We are using node <script>document.write(process.versions.node)</script>,
    Chrome <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.
  </body>
</html>
```

When right-click on `#appbar` element will reproduce the bug in frameless window. Enable the window frame will also reproduce the problem when right-click on the top draggable area.

## Your Environment
* Version used: iohook@0.4.6
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js v10.5.0, electron v5.0.3
* Operating System and version (desktop or mobile): Windows 10 x64

**Comment by DariusNorv** [comment]
Are there any updates here?

**Comment by Djiit** [comment]
Hey, could you please test with a more recent version of iohook ? LIke 0.6.4.

**Comment by DariusNorv** [comment]
@Djiit tested with 0.6.4 using electon 7. works fine. thnx.
