### ISSUE TITLE
System freezes Electron macOS

### ISSUE THREAD

**Issue by Faustus12** [wilix-team/iohook#178]
Hi! 

I use electron app on macOS with iohook and have problem with the system rights. It's not a problem to give the right to the app, but after that I have a system freezes for 2-3 sec every time when the new electron window opened or periodically system freezes during interaction with the any electron window. If unmark the checkbox near the app icon in the system right window it's working good. Give the rights again, freezes.

Any ideas?

Thanks!

**Comment by Djiit** [comment]
Hi there ! We're happy to help. Could you please use our provided template ? We need more information to help you out. Thanks

**Comment by Faustus12** [comment]
System freezes Electron macOS

## Expected Behavior
System security app rights granted, no freezes, collect user activity.

## Current Behavior
Periodically system freezes for 2-4 sec when use iohook library but only if the system security rights allowed for the app. Without the rights (forbidden or ignored) works well but not collect any activity. With the rights, collect activity but freeze the system during interaction with the electron window after appearing.

## Possible Solution
Have no idea.

## Steps to Reproduce (for bugs)
Quite difficult to reproduce this bug. I don't have any public repository for this project. I just use the template for electron + angular (https://github.com/maximegris/angular-electron) and add iohook library. Such freezes happen only in dist. No any freezes during debug in VS code, but after building the app as dmg and installing on mac i have this problem.

## Context
Periodically totally freeze the system.

## Your Environment
macOS Mojave v 10.14.5 desktop
Node.js v 10.16.0
Electron v 5.0.2
iohook v 0.4.6

**Comment by JSilversun** [comment]
I experienced the same problem with a simple electron demo I made with react + electron
macOS Mojave v10.14.0
Electron v4.0.4
iohook 0.5.0

**Comment by ape-casear** [comment]
same problem
macOS Mojave v10.14.6
Electron v5.0.11
iohook 0.6.5

**Comment by sibeshkar** [comment]
Has anybody figured out a fix to this? 2-3 second freeze with built electron app(error only in production). Thanks.

**Comment by ash0x0** [comment]
Can't repro this with Big Sur. Reopen if still an issue.
