### ISSUE TITLE
Missing release for node-v70

### ISSUE THREAD

**Issue by KYGAS** [wilix-team/iohook#181]
Can we get a release for node-v70 cause there isn't one atm?

## Expected Behavior
Requiring node-v70-win32-x64 and working

## Current Behavior

node-v70-win32-x64  doesn't exist

## Possible Solution

Make it if possible please, or if anyone has any idea how can I make it work?

## Context

Use iohook on app with node-v70

## Your Environment
Windows 64bit, Node-v70

**Comment by Djiit** [comment]
Hi, i'm looking at it right now but I can't find a 70 version for node (looked here : https://github.com/lgeiger/node-abi/blob/master/index.js). Maybe you meant electron ?

**Comment by KYGAS** [comment]
Sorry for the late response. here is the screenshot of the error that I've got:
http://prntscr.com/oeam1n
I tried running electron version as well but I've got an even weirder error:
http://prntscr.com/oeanee

I know that essentials is used for the path but I tried typing it manually since it didn't work either way...

Thanks in advance!

**Comment by Djiit** [comment]
Could you create a repo with a minimal reproductible example ? I'm sorry but I can't figure out how you can have node-v70 :(.

At least, can you paste here your actuel package.json ?

**Comment by KYGAS** [comment]
Here is a link towards the application that I am working with
[https://github.com/tera-toolbox/tera-toolbox](url)
Basically it's an app used to "inject" modules and such for the game Tera and I am trying to use key hooks for my module. But as you've seen, I get an error that node-v70 is needed.
If you have any ideas for the fix, like, trying to use some other version and such, please tell me and I'll try them, since otherwise you would have to download the whole game which is too much to ask for...

**Comment by KYGAS** [comment]
Sorry for raising the suspicion, for some reason, last time I tried using electron-v70 release it didn't work. However, now I tried again some things and I managed to load it.
So probably some bug or my mistake, you can consider this solved, thank you a lot.

I will open a new issue if I encounter some other problem.
