### ISSUE TITLE
Cannot find module 'iohook' after electron build for windows

### ISSUE THREAD

**Issue by Louis-7** [wilix-team/iohook#182]
## Expected Behavior
iohook should work after the electron build on Windows

## Current Behavior
iohook work well with `electron . --serve`. But after I build my App for Windows, it comes with error in console.
`ERROR Error: Cannot find module 'iohook'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584)
    at Function.Module._resolveFilename (C:\Users\ZHUANG~1\AppData\Local\Temp\1Nzoj211KqhjRAfUGyfOcRZNSQk\resources\electron.asar\common\reset-search-paths.js:43)
    at Function.Module._load (internal/modules/cjs/loader.js:510)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at new <anonymous> (main.9f9bdd10fb77e212e1ff.js:1)
    at main.9f9bdd10fb77e212e1ff.js:1
    at Ar (main.9f9bdd10fb77e212e1ff.js:1)
    at Pr (main.9f9bdd10fb77e212e1ff.js:1)
    at t.get (main.9f9bdd10fb77e212e1ff.js:1)`

## Possible Solution
no idea. Maybe it finds the wrong modulePath?

## Steps to Reproduce (for bugs)

1. include this in package.json
`  "iohook": {
    "targets": [
      "node-64",
      "electron-69"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }`
2. do `npm install`
3. build your app with `electron-builder build --windows`
4. run the .exe file then you will see errors in the console.

My project is based on https://github.com/maximegris/angular-electron and this is how I import electron in my project:

```typescript
import { Injectable } from '@angular/core';

// If you import a module but never use any of the imported values other than as TypeScript types,
// the resulting javascript file will look as if you never imported the module at all.
import { ipcRenderer, webFrame, remote, clipboard } from 'electron';
import * as childProcess from 'child_process';
import * as fs from 'fs';
import * as iohook from 'iohook';

@Injectable()
export class ElectronService {

  ipcRenderer: typeof ipcRenderer;
  webFrame: typeof webFrame;
  remote: typeof remote;
  clipboard: typeof clipboard;
  childProcess: typeof childProcess;
  fs: typeof fs;
  iohook: typeof iohook;

  constructor() {
    // Conditional imports
    if (this.isElectron()) {
      this.ipcRenderer = window.require('electron').ipcRenderer;
      this.webFrame = window.require('electron').webFrame;
      this.remote = window.require('electron').remote;
      this.clipboard = window.require('electron').clipboard;

      this.childProcess = window.require('child_process');
      this.fs = window.require('fs');
      this.iohook = window.require('iohook');
    }
  }

  isElectron = () => {
    return window && window.process && window.process.type;
  }

}
```

## Your Environment

* Version used: iohook 0.5.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): electron 4.2.6
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by Louis-7** [comment]
Got the answer. Since some native modules like iohook are not added into the "dependencies" in the package.json, so it's not compiled into the final package. 

Close this issue now.

**Comment by karacas** [comment]
Maybe this help:
[https://github.com/wilix-team/iohook/issues/160](url)

**Comment by Louis-7** [comment]
Thank you @karacas, I think this issue is not like yours, I forgot to add iohook as a node dependency so it's not included in the final package.

But thank you for your suggestion!
