### ISSUE TITLE
Why is iohook so performance heavy on windows?

### ISSUE THREAD

**Issue by ImUrX** [wilix-team/iohook#183]
So I have an small app (bongo-cat) which just detects the pressing down and up of 2 keys, why is it so performance-heavy that I can't run it 2 times and make them work ON windows

## Expected Behavior

well i tried my app in linux and it worked pretty ok and 2 of them worked ok without impacting my computer in comparation of windows, idk if the problem its from how the windows part of the c library works, i need to read it and im pretty bad at C

## Current Behavior

doesnt even detect the keys and perfomance is pretty bad and the first one shouldnt happen

## Possible Solution

as i said i need to read sorry for making a useless issue without a solution to it

## Steps to Reproduce (for bugs)

https://github.com/ImUrX/bongo-cat/releases/tag/v1.0.1
(tell me if its my fault, its my first electron app lol)

## Context

well someone asked me for his streaming app, and he told me it worked pretty badly when he ran 2 of them but i didnt see much that i could optimize that can affect this issue

## Your Environment

* Version used: v0.5.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v12.6.0, electron v5.0.6
* Operating System and version (desktop or mobile): Windows 7 x64
* Link to your project: https://github.com/ImUrX/bongo-cat

**Comment by ImUrX** [comment]
sorry for the aggressive issue :P

**Comment by Djiit** [comment]
Hi there,

You are indeed not using the best practices for an Electron app. Do you have numbers we could use ? Does it take all your RAM ?

We need a bit more information to further help you.

**Comment by ImUrX** [comment]
yeah thanks for the first part (not sarcasm tbh)
and no, it doesnt use all ram, i suspect its how it works on windows but i never coded in low-level on windows 
numbers:
Process: https://gfycat.com/WindingFamousCottonmouth
Performance: https://gfycat.com/ImpeccableDiligentCub
btw if you have any nice eh best practices for an electron app, call me pls

**Comment by ash0x0** [comment]
Closing as irrelevant. Performance is actually fine on windows, not sure if user error or potato pc :D or otherwise but feel free to reopen.

**Comment by ImUrX** [comment]
yeah not the best issue i have done, but im sure its because of the reasons specified by djiit

**Comment by ash0x0** [comment]
@ImUrX If you're still experiencing this issue please feel free to let me know to reopen and investigate further.
