### ISSUE TITLE
Can't npm install, due to wrong github team name in the link

### ISSUE THREAD

**Issue by georgejecook** [wilix-team/iohook#188]
Can't install - seems the name of your team has changed

## Expected Behavior
when doing npm install, with the default package.json settings (which match my electron setup), it should install the package

## Current Behavior
does not install does..
GET https://github.com/WilixLead/iohook/releases/download/v0.6.0/iohook-v0.6.0-electron-v57-darwin-x64.tar.gz returned 404

## Possible Solution
I can see the actual link is https://github.com/wilix-team/iohook/releases/download/v0.6.0/iohook-v0.6.0-node-v57-darwin-x64.tar.gz

seems your team name changed from `WilixLead` to `wilix-team`

## Steps to Reproduce (for bugs)
1. add the following to package.json
 "iohook": {
    "targets": [
      "node-59",
      "electron-57"
    ],
    "platforms": [
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
2. so npm install
3.
4.

## Context
can't get started

## Your Environment
* Environment name and version (e.g. Chrome 39, node.js 5.4):
electron 4
node 9.9
* Operating System and version (desktop or mobile):
mac 10.13.4

**Comment by Djiit** [comment]
Ahem, it seems the old redirection by Github is not live anymore. Just fixed this in 0.6.1, waiting for the CI to pass.

**Comment by Djiit** [comment]
Fixed in 0.6.1. Thanks !

**Comment by georgejecook** [comment]
This doesn't work

Downloading prebuild.tar.gz
Error: GET https://github.com/wilix-team/iohook/releases/download/v0.6.1/iohook-v0.6.1-electron-v57-darwin-x64.tar.gz returned 404
Prebuild for current platform (iohook-v0.6.1-electron-v57-darwin-x64) not found!

**Comment by Djiit** [comment]
Oh I see. it wasn't a redirection issue (but the fix is great anyway).
Electron 2.0 is not officially supported since version 0.6.0 (see README / CHANGELOG). What you can do is : 
- Use 5.X version
- Upgrade to Electron 4, 5 or 6.
