### ISSUE TITLE
The message "would like to control this computer using accessibility features"

### ISSUE THREAD

**Issue by trae-op** [wilix-team/iohook#192]
After each app start display the message "**would like to control this computer using accessibility features**". Even if you just add `const ioHook = require('iohook');` the message will display. 
I use **electron v6.0.1**
I have **high sierra 10.13.3**

![image](https://user-images.githubusercontent.com/12648541/63100746-61db6c80-bf80-11e9-90e6-f3dc91d7d9f4.png)

**Comment by Djiit** [comment]
Hello,

This is an intended behavior on macOS. Maybe we should state it more clearly in the README ?

**Comment by jbagaresgaray** [comment]
Possible duplicate issue on https://github.com/wilix-team/iohook/issues/107

**Comment by Djiit** [comment]
Duplicate of #107
