### ISSUE TITLE
error on install iohook return page not found

### ISSUE THREAD

**Issue by FordeD** [wilix-team/iohook#194]
install iohook find version on https://github.com/wilix-team/iohook/releases/download/v0.6.1/iohook-v0.6.1-electron-v54-win32-x64.tar.gz page
but this page return "Not found".

I use this module with electron.

console return on install npm:
```
> iohook@0.6.1 install D:\js\electron\program\node_modules\iohook
> node install.js

node 59 win32 x64
Downloading prebuild for platform: iohook-v0.6.1-node-v59-win32-x64
Downloading prebuild.tar.gz
[============================================>] 100.0% of 29.9 kB (29.9 kB/s)
Downloading prebuild.tar.gz
[============================================>] 100.0% of 25.37 kB (25.37 kB/s)
Downloading prebuild.tar.gz
[============================================>] 100.0% of 25.54 kB (25.54 kB/s)
Downloading prebuild.tar.gz
Error: GET https://github.com/wilix-team/iohook/releases/download/v0.6.1/iohook-v0.6.1-electron-v54-win32-x64.tar.gz returned 404
Prebuild for current platform (iohook-v0.6.1-electron-v54-win32-x64) not found!
Try to compile for your platform:
# cd node_modules/iohook;
# npm run compile


D:\js\electron\program\node_modules\iohook\install.js:15
  throw err;
  ^
Prebuild for current platform (iohook-v0.6.1-electron-v54-win32-x64) not found!
npm WARN babel-loader@8.0.6 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN brainmacros@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.6.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\seda1\AppData\Roaming\npm-cache\_logs\2019-09-09T18_08_38_404Z-debug.log```

**Comment by Djiit** [comment]
Hi! Can you paste here your package.json ?

**Comment by FordeD** [comment]
> Hi! Can you paste here your package.json ?

```
{
  "name": "brainmacros",
  "version": "1.0.0",
  "description": "Brain Macros on NodeJS",
  "main": "src/app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "play": "./node_modules/.bin/electron .",
    "watch": "./node_modules/.bin/webpack-dev-server",
    "electron-rebuild": "./node_modules/.bin/electron-rebuild",
    "rebuild": "npm rebuild --runtime=electron --target=1.1.3 --disturl=https://atom.io/download/atom-shell --abi=48"
  },
  "author": "FordeD",
  "license": "ISC",
  "dependencies": {
    "electron": "^6.0.3",
    "electron-rebuild": "^1.8.6",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "robot-js": "^2.0.0"
  },
  "devDependencies": {
    "babel": "^6.23.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.6",
    "babel-preset-react": "^6.24.1",
    "webpack": "^4.39.2",
    "webpack-dev-server": "^3.8.0"
  },
  "config": {
    "appname": "Application",
    "electronversion": "0.33.3",
    "appsrc": "src/",
    "builddir": "build",
    "apppackage": "x64"
  },
  "files": [
    "*.js",
    "build",
    "node_modules"
  ],
  "iohook": {
    "targets": [
      "node-59",
      "electron-54"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
  "robotjs": {
    "targets": [
      "node-59",
      "electron-54"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
}
```

**Comment by Djiit** [comment]
Hi there, can you try with version 0.6.2 ?

**Comment by dev-yogesh** [comment]
Tried version 0.6.2 but the same issue.
![Screenshot from 2020-11-23 00-19-57](https://user-images.githubusercontent.com/25033425/99914191-b348de80-2d21-11eb-9401-d1976fb4b644.png)

**Comment by dev-yogesh** [comment]
**node-vXX**  is the issue.  Similar will be with electron in future. 

**install.js file line number 32.**  construction of a download url is causing the trouble, due to updated node versions being used.
![issue](https://user-images.githubusercontent.com/25033425/99914422-54846480-2d23-11eb-9169-df0d987f4f11.png)

**Comment by messerbill** [comment]
This is still not working after more than a year

**Comment by Patrick1982** [comment]
it worked for me with these versions:
"electron": 4.1.4
"iohook": 0.4.4
"node": 10.23.2

**Comment by brijcodeclouds** [comment]
Facing similar issue 
`"targets": [
      "node-72",
      "electron-80"
    ],`

Prebuild for current platform (iohook-v0.7.2-node-v72-linux-ia32) not found!
Please suggest @Djiit

**Comment by WilixLead** [comment]
@brijcodeclouds 
> Prebuild for current platform (iohook-v0.7.2-node-v72-linux-ia32) not found!

It is because iohook don't support ia32 arch for linux. You can compile it manually (I think it require some changes in current sources) or just don't use x32

**Comment by PxlLoewe** [comment]
Same problem here:

E:\Dev\vHEMS_v2\client\electron-app>npm i iohook
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> iohook@0.9.1 install E:\Dev\vHEMS_v2\client\electron-app\node_modules\iohook
> node install.js

Downloading prebuild for platform: iohook-v0.9.1-node-v83-win32-x64
Downloading prebuild.tar.gz
Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v83-win32-x64.tar.gz returned 404
Prebuild for current platform (iohook-v0.9.1-node-v83-win32-x64) not found!
Try to build for your platform manually:
# cd node_modules/iohook;
# npm run build

E:\Dev\vHEMS_v2\client\electron-app\node_modules\iohook\install.js:16
  throw err;
  ^

[Error: ENOENT: no such file or directory, open 'C:\Users\joamb\AppData\Local\Temp\prebuild.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\joamb\\AppData\\Local\\Temp\\prebuild.tar.gz'
}
npm WARN electron-app@1.0.0 No description
npm WARN electron-app@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.9.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joamb\AppData\Roaming\npm-cache\_logs\2021-06-03T17_18_08_126Z-debug.log

**Comment by ash0x0** [comment]
refer to #335
