### ISSUE TITLE
No events when app is in focus after calling getUserMedia() on windows

### ISSUE THREAD

**Issue by dominik-vincenz** [wilix-team/iohook#196]
## Expected Behavior
keydown events should be sent when the electron app is in focus and also when the app is not in focus

## Current Behavior
After calling **navigator.mediaDevices.getUserMedia** in renderer process all events stop being sent when the app is in focus.
Before calling getUserMedia it works like described in "Expected Behavior"

**Issue seems to appear only on windows. On Mac OS it workes fine**

## Steps to Reproduce (for bugs)
Sample app can be found here:
https://github.com/dominik-vincenz/iohook-issue-sample

1. Start provided electron app and type sth. while the app is in focus and out of focus
2. In the electron log all keypressed are logged
3. Click Button "GetUserMedia"
4. Type again with app in focus and out of focus. 
5. Keypresses are not only logged when the app is not in focus

## Your Environment
electron-5.0.10
windows 10
iohook-0.6.1

**Comment by enzious** [comment]
what the flib, I was just about to open this issue.

**Comment by chevonc** [comment]
I think I may be hitting this issue as well. Not sure what the cause in. Running electron 6.0.5

**Comment by enzious** [comment]
Could a developer chime in on this and help me get started on tracking this down? Like any ideas where to start diagnosing this. I'm willing to chase this down into Chromium with some better direction.

**Comment by adambailey-** [comment]
We're experiencing this issue as well on Electron 5.0.10

**Comment by enzious** [comment]
I am still getting this issue on Electron 8.x

**Comment by enzious** [comment]
Found a resolution: https://github.com/wilix-team/iohook/issues/230#issuecomment-611566872

**Comment by ash0x0** [comment]
Closing as stale and probably resolved.
