### ISSUE TITLE
Down key (down arrow) and Function Keys not detected by keypress Listener

### ISSUE THREAD

**Issue by jzxhuang** [wilix-team/iohook#198]
Hey! First of all, awesome library - exactly what I'm looking for! I'm have some issues with the "keypress" listener - I'm not sure how much of it is due to incomplete implementation of keypress? Also not sure if it's macOS specific or not, don't have a windows/linux machine to test on right now. 

It looks like it may be related to #54 - does not look like it's been fixed though

## Expected Behavior
* The "keypress" listener should detect when I press the down arrow key
* The "keypress" listener should detect function keys

## Current Behavior
* The keypresses are not detected

## Notes
* up/left/right arrow keys are detected, and all other keys as far as I can tell except for down arrow key and function keys
* Taking a brief glance at the debugger, it looks like it might be an issue with `dispatch_sync_f`? Not too familiar with low-level/ haven't looked too carefully
* All keys seem to work when using keyup/keydown listeners.

## Steps to Reproduce (for bugs)
Here's my code
```js
"use strict";

const { app } = require("electron");
const ioHook = require("iohook");

function eventHandler(event) {
  console.log(event);
}

app.on("ready", () => {
  ioHook.start(true);
  ioHook.on("keypress", eventHandler);
  ioHook.on("keyup", eventHandler);
  console.log("Try move your mouse or press any key");
});

app.on("before-quit", () => {
  ioHook.unload();
  ioHook.stop();
});
```

## Context
For my use case I'd like to specifically detect key presses

## Your Environment

* Version used: 0.6.1
* Environment name and version: Node 12.9.1, Electron 6.0.12. Also reproduced on Node 10.16.3, Electron 4.1.4
* Operating System and version: macOS 10.14.6 (Mojave)
* Link to your project: N/A

Thanks for your help and let me know if I can provide any other details!

**Comment by ash0x0** [comment]
Can't repro. Closing as irrelevant, possibly/probably fixed.
