### ISSUE TITLE
Cannot find module electron-v75-win32-x64 iohook.node

### ISSUE THREAD

**Issue by aizaku** [wilix-team/iohook#200]
Hi,
Trying to use iohook for my app. After installing and running the app I get:
`Cannot find module '(...)\node_modules\iohook\builds\electron-v75-win32-x64\build\Release\iohook.node`
The **iohook\builds** folder contains only **node-v64-win32-x64** directory. How do I get **electron-v75-win32-x64** for it to work? Can you prebuild it and send it?

Module versions:
"electron": "^7.0.0"
"iohook": "^0.6.1",
npm v6.9.0
node v10.16.3

**Comment by Djiit** [comment]
Hi, this package is not yet compatible with Electron 7.0.0. Closing for #199
