### ISSUE TITLE
Hook Sometimes Thinks Keys Are Down When Not

### ISSUE THREAD

**Issue by metal450** [wilix-team/iohook#203]
I'm using an iohook to do something on Windows whenever a hotkey combination (control+space) is pressed.  Here's the code:

    const ioHook = require("iohook");
    ioHook.on("keypress", (event) => {
        if (event.ctrlKey && event.keychar == 32) {
            doIt();
        }
    });
    ioHook.start();

The problem is, sometimes - randomly - it starts firing when I *only* type the spacebar (control is not held down).  I can keep pressing just spacebar, and it keeps firing.  If I then press control once, it "un-sticks," and I can again use the spacebar normally.

* iohook version: 0.6.1
* OS: Windows 10 LTSC 2019
* Node: 10.16.3

**Comment by pgupt** [comment]
I have similar issue. I opened another ticket. I think this is because iohook remembers previous events even when iohook.stop is called. It should actually reset the events.

**Comment by metal450** [comment]
Link to the other ticket?

**Comment by pgupt** [comment]
https://github.com/wilix-team/iohook/issues/220 
I have closed this ticket. It was issue with my knowledge of Vuejs.

**Comment by metal450** [comment]
Ah, gotcha, thanks.

**Comment by borsTiHD** [comment]
I also have some similiar behaviour with my registered hotkey (`STRG+<`).
My hotkey is sometimes triggered by just pressing `STRG`.

```
// STRG+<
this.globalHotkeys.clipboardCheck = ioHook.registerShortcut([29, 0], (keys) => { }, (keys) => { // STRG+<
    this.hotkeyFunction('hotkeyEvent')
})
```

I'm trying `ioHook.stop()` and `ioHook.start()` with setTimeout functions as a workaround, but it didn't work so well. :(

**Comment by ash0x0** [comment]
This seems to not be a current issue. Please reopen if it is and I will investigate.
