### ISSUE TITLE
sometimes "captures" too much

### ISSUE THREAD

**Issue by briiju** [wilix-team/iohook#204]
This library was used in order to sense mouse/keyboard activity at one of my customers.

Their issue was when they used a barcode scanner in an electron app, it would truncate the first half of the barcode string (in HID mode, so it was acting as a keyboard wedge).

As soon as the library was removed, this issue was no longer existent

**Comment by ash0x0** [comment]
Not sure if this is an issue still but if so then really can't repro or fix, simply because no barcode scanner and it's a niche use case. Feel free to open and PR if this is an issue for you.
