### ISSUE TITLE
Does not work on ARM (Raspberry PI)

### ISSUE THREAD

**Issue by computersrmyfriends** [wilix-team/iohook#21]
Hi,
I tried npm install and I also tried compiling this from source.
Compiling from source also does not work for this package. I tried "npm run build" after installing cmake and cmake-js. No success. Please see screenshot.
![image](https://user-images.githubusercontent.com/323931/27581107-4b0f6782-5b4a-11e7-82f1-7ce4197c6753.png)

Thanks.

**Comment by WilixLead** [comment]
You should install all needed packages to your system.
Error says you don't have "autoreconf" command and may be something else.
Please look to this [Manual Install](https://github.com/WilixLead/iohook#manual-compilation-for-your-version-of-environment)

May be for your system need additional install for autoreconf like for macOS
`apt install cmake automake libtool pkg-config` or something like this

**Comment by cerw** [comment]
I have no success either 


```
/bootstrap.sh: 3: [: Linux: unexpected operator
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:76: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:99: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
autoreconf: /usr/bin/autoconf failed with exit status: 1
CMakeFiles/prepare_iuhook.dir/build.make:57: recipe for target 'CMakeFiles/prepare_iuhook' failed
make[2]: *** [CMakeFiles/prepare_iuhook] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/prepare_iuhook.dir/all' failed
make[1]: *** [CMakeFiles/prepare_iuhook.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
ERR! OMG Process terminated: 2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.1.13 build: `cmake-js compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.1.13 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

```

**Comment by WilixLead** [comment]
Looks like you don't install libtool. Please try install / reinstall libtool and compile again

**Comment by Djiit** [comment]
We might need some help here. If anyone has a spare Raspberry or another ARM device, could you try to compile libiohook ? And then update the documentation.

**Comment by michaltaberski** [comment]
I have no luck to get it working neither. 

Does it work for anyone on Raspberry?

@Djiit how can I help to compile `libiohook` ?

**Comment by Djiit** [comment]
Hi there, you could try to compile manually this : https://github.com/kwhat/libuiohook
And report here your errors. Thanks !

**Comment by michaltaberski** [comment]
Ok, the first moment where I stucked and google didnt help is

```
configure: error: Package requirements (xkbfile) were not met:

No package 'xkbfile' found
```

on  `./configure` run

**Comment by Djiit** [comment]
Try to install `libxkbfile-dev`

**Comment by Djiit** [comment]
I see. Try the following : 

- Clone this repository in you node_modules folder.
- Go into it, into the libuiohook folder
- Compile libuiohook as you did before
- go back into the iohook folder and run `npm run build`

**Comment by michaltaberski** [comment]
I did all the steps, now when I run my app

`node index.js`

```
const ioHook = require('iohook');

ioHook.on("keydown", event => {
console.log(event);
});

//Register and start hook
ioHook.start();
```

I am getting

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/home/pi/projects/keyboard/node_modules/iohook/builds/node-v59-linux-arm/build/Release/iohook.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
```

I also wanted to say found solution for the issue I wanted to solve with `iohook`, so I don't need it anymore. However I am happy to help you figuring out how to get `iohook` working on raspberry, so let me know if you have any further instructions.

**Comment by michaltaberski** [comment]
@komorebi-san no, I didn't. In the end I went totally different way. I created a small node server which provides website. The website is connected with node server via websocket and on each key press i was interested in I was transmitting the input to the node. Crazy, but it was exactly what I needed.

**Comment by GFargo** [comment]
In a similar situation, would love to get this working on the RasPi but after trying to manually compile `libiohook` and getting no where I'm leaning towards going down a similar path as @michaltaberski.  

That said, it would be pretty wonderful to have ARM support so if there's anything I can do to assist with debugging please let me know!

**Comment by komorebi-san** [comment]
@michaltaberski @GFargo 

I am also doing exactly the same thing. Just a simple website that connects via socket.io

**Comment by Jonathan-Engel** [comment]
I was able to compile `libiohook` on a PI, I'll retrace my steps and put a PR in updating the docs when I get home. I compiled it using Ubuntu MATE... I didn't have much success with Raspbian. 

However the binary DOES work on Raspbian once its compiled (at least it does for me). 

[node-v72-linux-arm.tar.gz](https://github.com/wilix-team/iohook/files/3483072/node-v72-linux-arm.tar.gz)

[node-v72-linux-arm.zip](https://github.com/wilix-team/iohook/files/3483073/node-v72-linux-arm.zip)

**Comment by freenerd** [comment]
An alternative for other Raspberry Pi users landing here: The [input-event](https://www.npmjs.com/package/input-event) library works directly on ARM without problems. It is also significantly less powerful than iohook. Still might be a solution for some.

**Comment by ash0x0** [comment]
Closing as stale. Anyone interested please reopen and if you can, please PR.
