### ISSUE TITLE
Is it possible to make it faster?

### ISSUE THREAD

**Issue by Sentero-esp12** [wilix-team/iohook#210]
## Expected Behavior
Keys are captured without any significant delay.

## Current Behavior
There is a delay of 200-1000ms (or even more).

## Possible Solution
Increase the speed of polling if it uses polling. 

## Steps to Reproduce (for bugs)
Console.log events and you can see that there is some delay. 

1.
2.
3.
4.

## Your Environment

* Version used: 0.6.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v12.13.0
* Operating System and version (desktop or mobile): Windows 7 64
* Link to your project: 

I've tried "mousemove" and "keydown", but they seem to have some delay, around 300-1000ms (I'm working on a script to control two computers with the same keyboard). 
Especially when I'm writing fast, it waits a second or two before sending the keys.
Is it using polling to capture events? 
Could it be made faster or poll at higher frequencies? Or this is the maximum possible speed?

**Comment by hediet** [comment]
It's fast on windows 10 though, there is no noticable delay.

**Comment by VSDekar** [comment]
Same here. No Delay

**Comment by Sentero-esp12** [comment]
Yes, sorry, now I don't see any delay either. It was probably something else.
