### ISSUE TITLE
ioHook keeps capturing even in background

### ISSUE THREAD

**Issue by ackvf** [wilix-team/iohook#213]
> How do I tell when the terminal is not focused so that I can ignore the events?

Is it normal that this library keeps capturing keys in background and even when filling a password in this kind of prompt?

![image](https://user-images.githubusercontent.com/2313018/73123134-cb7a9080-3f8c-11ea-8eff-582c50567849.png)

**Comment by pgupt** [comment]
have you tried iohook.stop() when you don't want iohook to capture?

**Comment by ackvf** [comment]
The thing is, I still need focus / blur events of the window so that I can stop listening.

**Comment by pgupt** [comment]
@ackvf you can keep a flag for when you want to listen or not. If flag == false, then don't do anything. This way iohook is still listening but is not doing anything.

**Comment by ackvf** [comment]
@pgupt What do you mean? Is the "flag" you mention some core iohook feature? Can you point me to docs where this is explained more?

I am not sure if we understand each other correctly - for me to be able to stop doing anything, I first need to know when the window is focused or not.

**Comment by pgupt** [comment]
@ackvf I might have explained it in a bad way. Sorry. 
You can define a boolean flag in your code. Make it false when you don't want to act on certain events say keypress. 

Then when you get such event you simply return. e.g.
iohook.on('keypress', (event) => {
   if(flag == false){
      //do nothing
      return
   }
}

**Comment by ackvf** [comment]
@pgupt Right, but then I first need to know when to switch the flag, ie. know when the window is unfocused/focused. Any ideas?

**Comment by pgupt** [comment]
@ackvf  sure. Are you using Electron? There are ways to find if window is focused or not.

**Comment by ackvf** [comment]
No, just a terminal, mostly windows cmd, but I may start using git-bash or different bash emulator under windows if there turn out to be limitations.

**Comment by Djiit** [comment]
Hey, just to complement the anwsers here, iohook is **intended** to capture everything. You should** warn your users and/or be precise about what you record or not.

**Comment by pgupt** [comment]
@ackvf If you are writing script then there are ways to find which application is in foreground and get their pid or process name. It is extra step and adds to complexity but you can't do anything else.

**Comment by ackvf** [comment]
Does ioHook help with it, for example by emiting focus/blur events by any chance?

**Comment by pgupt** [comment]
@ackvf iohook won't help with focus/ blur event afaik. You are using Powershell to code right?

**Comment by ackvf** [comment]
No, I am using `cmd` primarily, then `git-bash`.

**Comment by ash0x0** [comment]
So it's basically almost nearly impossible to tell if the user is currently entering a password or not unless the OS provides an API for that and I double microsoft massively improved windows APIs since the last time I looked. I would suspect Mac Catalina and higher would probably have this automatically blocked already. 
That being said, this is not only intended behavior but there really is no feasible cross-platform way to avoid it automagically.
The best you can do is stop capture when not in focus OR provide some sort of input/toggle for the user themselves to stop capturing temporarily and then resume when they wish. In a CLI I suggest providing some input for the user to do that.

**Comment by ackvf** [comment]
@ash0x0 Thanks for the input. How can I know when the CLI is in focus or not so that I can disable/enable capturing?

This is especially useful when running two instances at the same time.
