### ISSUE TITLE
Error: Cannot find module 'iohook'

### ISSUE THREAD

**Issue by suravdalyan** [wilix-team/iohook#224]
The error still available on Windows( tested on 7 and 10) for this configs:

`"iohook" : {
    "targets": [
      "node-72",
      "electron-75"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }`
 
All is okay on devices where installed Microsoft Visual C++. But on devices  where isn't installed Microsoft Visual C++, I get an error after
const ioHook = require('iohook');

![image](https://user-images.githubusercontent.com/25320738/75036743-04dee700-54cc-11ea-90f5-3ee3f233bd16.png)

**Comment by masudhossain** [comment]
any updates to this?

**Comment by Tschuck** [comment]
> any updates to this?

Hi @masudhossain and @suravdalyan! I also had this issue, it occures when configuring the wrong electron version with the wrong iohook flags.

I'm currently running with this versions:

- electron: ^8.0.0
- iohook configuration in package.json

```
"iohook": {
    "arches": [
      "x64",
      "ia32"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "targets": [
      "electron-76"
    ]
  },
```
 
Hope it helps :)

**Comment by zxc23** [comment]
Looks like the same problem as #195 

I am experiencing it with

`"iohook": {
    "targets": [
      "node-72",
      "electron-75"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }`

and Electron ^7.1.4

**Comment by Liu98Fan** [comment]
Hi @suravdalyan ,From your information,I think you don't have the library`electron-v75-win32-x64` in `node_moudules` folder,
try this config in your `package.json`
`"iohook" : { "targets": [ ,"electron-75" ], "platforms": [ "win32" ], "arches": [ "x64" ] }`
then rebuild the library via the command
`npm rebuild --runtime=electron --target=x.y.z --disturl=https://atom.io/download/atom-shell --abi=75`
the `x.y.z` in this command is your electron version
it will try to download the `electron-v75-win32-x64` file
if there's no error,you will see the `electron-v75-win32-x64` file in your `node_modules`folder,and you can run your application successfully.
if you find something like this:
`
....
Error: electron-v75-win32-x64 not found! you can try to build it mantually
...
`
i guess that author haven't prebuild the ihook matching this electron version ,maybe you have two choice:

1. build this version mantually,and i have not  try it yet
2. replace your electron  with other version which have been prebuild 

i'm using the `8.0.0` version,it is appropriate working with 'electron-v76-win32-x64' file,you can try it. hope you succeed！

**Comment by zxc23** [comment]
An update: I've had multiple confirmations that this problem was resolved by installing Microsoft Visual C++ Redistributable on the machines via https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads.

These issues are all related:

#167
#193
#195
#224 
#245

**Comment by omiinaya** [comment]
> > any updates to this?
> 
> Hi @masudhossain and @suravdalyan! I also had this issue, it occures when configuring the wrong electron version with the wrong iohook flags.
> 
> I'm currently running with this versions:
> 
> * electron: ^8.0.0
> * iohook configuration in package.json
> 
> ```
> "iohook": {
>     "arches": [
>       "x64",
>       "ia32"
>     ],
>     "platforms": [
>       "win32",
>       "darwin"
>     ],
>     "targets": [
>       "electron-76"
>     ]
>   }
> ```
> 
> Hope it helps :)

this solved my issue! thanks a lot!

**Comment by ash0x0** [comment]
Closing as resolved.
