### ISSUE TITLE
electron install iohook Caton

### ISSUE THREAD

**Issue by DH-Y** [wilix-team/iohook#242]
I'm developing an electronic desktop,  npm install iohook , If ‘const iohook = require('iohook')’ ，The mouse is stuck when the program starts,  But cancel the import and return to normal.
I hope you can answer.

**Comment by DH-Y** [comment]
Hello, I've solved it.
terms of settlement:
·~before:
const ioHook = require("iohook");

function demo(){
   ioHook.on('mousemove',function)
}

·~after:
const ioHook = null

function demo(){
  ioHook=require("iohook");
   ioHook.on('mousemove',function)
}

Solve the problem of mouse jam when Electron npm run

**Comment by adi-kurnia** [comment]
Hello, nice to meet you.
Same issue with you here.
Could you share whole js file including iohook declaration?
I'd like to take a look at it.
Thank you.

**Comment by ash0x0** [comment]
Closing as stale. Also seems to be user error. Feel free to reopen if this is a current issue.
