### ISSUE TITLE
iohook not found with Electron

### ISSUE THREAD

**Issue by PiggyPlex** [wilix-team/iohook#245]
## Expected Behavior
iohook should work. Would like to use iohook in the front-end however cannot get it to work.

## Current Behavior
![image](https://user-images.githubusercontent.com/15018948/87247065-4d7e4900-c449-11ea-9438-d8f51295e651.png)
Tried generating ABIs for both NodeJS and Electron and added sufficient parts to package.json. Have tried uninstalling, reinstalling, using https://www.electronjs.org/docs/tutorial/using-native-node-modules. Read multiple bug reports and articles and watched videos all to no avail. I believe it might be to do with Electron running a separate runtime version, however I've even tried editing the code to require the file by its absolute path and that still does not work.

## Steps to Reproduce (for bugs)

1. Install iohook using NPM (`npm i iohook -s`)
2. Run Electron (`electron .`)
```js
const electron = require('electron'),
          iohook = require('iohook');
```

## Context

Trying to do keystroke and mouse detection for an on-screen counter in Electron.

## Your Environment

* Version used: v0.6.6
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.JS v11.10.1; Electron v9.1.0
* Operating System and version (desktop or mobile): Desktop (Windows 10)
* package.json:
```json
  "iohook": {
    "targets": [
      "node-67",
      "electron-80"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
```

**Comment by marcelblum** [comment]
iohook does not yet work with Electron 9 on Windows and 0.6.6 failed to achieve compatibility, see https://github.com/wilix-team/iohook/issues/241. On Windows for iohook to work you must use Electron <9.

**Comment by PiggyPlex** [comment]
Still get the same issue after downgrading to Electron 8.3.4 despite someone saying that works in the post.

**Comment by marcelblum** [comment]
For Electron 8.3.4 your package json should now have
`"targets": [
      "electron-76",
      "node-72"
    ]`
for Electron 8 and Node 12. Node 12.13.0 is the one paired with Electron 8.3.4. Unless you are intentionally using a different Node version with your Electron setup (you mentioned Node.JS v11.10.1 above)?

**Comment by ghmendonca** [comment]
I am using node 12.13.0 and iohook 0.6.6 on windows and doesn't work, I get the same error saying the module was not found even the module is there. I tried adding the targets to my package json and still doesn't work.

Any idea why it doesn't work?

**Comment by PiggyPlex** [comment]
Node.JS v11.10.1 is working with Electron and is not the issue.

**Comment by PiggyPlex** [comment]
Unless there are features in v12 which iohook utilises which causes an error, however it seems unlikely.

**Comment by ghmendonca** [comment]
Just checked with node v11.10.1 and doesn't work as well :/

**Comment by akbar-animaker** [comment]
any update on this... i am facing the same issue

**Comment by zxc23** [comment]
An update: I've had multiple confirmations that this problem was resolved by installing Microsoft Visual C++ Redistributable on the machines via https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads.

These issues are all related:

#167
#193
#195
#224 
#245

**Comment by danikoala** [comment]
What about Mac users? Right after I call require('iohook'), my electron process stops:

Process exited with code 0

I'm using electron 9.1.2

**Comment by PiggyPlex** [comment]
I've reinstalled Microsoft Visual C++ Redistributable and reinstalled iohook with no avail.

**Comment by messerbill** [comment]
@marcelblum thank you very much....no docs where telling that stuff in that explicit form like you did.

**Comment by PiggyPlex** [comment]
Any update?

**Comment by marcelblum** [comment]
@PiggyPlex lot of updates to iohook since you originally posted, have you tried the latest version, which now works through latest Electron v11.x?

**Comment by joaomendoncaa** [comment]
@marcelblum I'm having the same issue... 

Error: Cannot find module 'D:\myprojects\full-projects\bindbox\node_modules\iohook\builds\electron-v85-win32-x64\build\Release\iohook.node'

Any feedback on this issue?

**Comment by zhouyi19980603** [comment]
> @marcelblum I'm having the same issue...
> 
> Error: Cannot find module 'D:\myprojects\full-projects\bindbox\node_modules\iohook\builds\electron-v85-win32-x64\build\Release\iohook.node'
> 
> Any feedback on this issue?

你解决了吗

**Comment by joaomendoncaa** [comment]
> 
> 
> > @marcelblum I'm having the same issue...
> > Error: Cannot find module 'D:\myprojects\full-projects\bindbox\node_modules\iohook\builds\electron-v85-win32-x64\build\Release\iohook.node'
> > Any feedback on this issue?
> 
> 你解决了吗

No, i had to use an older version of electron and electron-rebuild package.
