### ISSUE TITLE
Supported Latest Versions

### ISSUE THREAD

**Issue by kirkcharlesniv** [wilix-team/iohook#247]
According to the [FAQ](https://github.com/wilix-team/iohook#faq), they are trying to match with the latest current version of [Node.js](https://nodejs.org/en/about/releases/) [v10, v12, v14] and [Electron](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions) [9.x.y, 8.x.y, 7.x.y].

But according to their [Installation Guide](https://wilix-team.github.io/iohook/installation.html), it currently supports Electron 2.X, and Node.js 10.0.X.

Is it still possible to use iohook for v14 of Node.js, and 9.x.y of Electron?

**Comment by suresh-borad** [comment]
@kirkcharlesniv not working for me also. I'm trying with latest node and electron but it's show `exited code with 0`

**Comment by danikoala** [comment]
+1. Electron v9.12, Node v.12.12.0

**Comment by patrykscheffler** [comment]
Any updates on supporting the latest electron version? My application also crashes after initializing this library `Process exited with code 0` on macOS.

Electron v9.1.2, Node v14.7.0, iohook v0.6.6

**Comment by VuHoi** [comment]
> Any updates on supporting the latest electron version? My application also crashes after initializing this library `Process exited with code 0` on macOS.
> 
> Electron v9.1.2, Node v14.7.0, iohook v0.6.6

Me too.:((

**Comment by Djiit** [comment]
Closing as a duplicate of https://github.com/wilix-team/iohook/issues/241
