### ISSUE TITLE
Process finished with exit code -36861

### ISSUE THREAD

**Issue by a-keramat** [wilix-team/iohook#253]
## Current Behavior
I get this error 
```
. . .\Electron\build\node_modules\electron\dist\electron.exe .


Process finished with exit code -36861
```

when trying to require ihook as below :

`const ioHook = require('iohook');`

## Your Environment
Win 10 | node v12.18.4 | electron v10.1.3 | iohook 0.6.6

Package.json : 
```
"iohook": {
    "targets": [
      "node-72",
      "electron-80"
    ],
. . . .
}
```

**Comment by marcelblum** [comment]
Latest iohook 0.6.6 can only work with Electron up to 8.x.x unfortunately.

**Comment by ash0x0** [comment]
Closing as irrelevant.
