### ISSUE TITLE
build assets manually for electron 10.1.1, and set app.allowRendererProcessReuse = false, the application process can't start again..

### ISSUE THREAD

**Issue by quanweibai** [wilix-team/iohook#254]
built assets for electron 10.1.1 manually,  and add .node file to node_modules, after that, got the error msg:
   **Uncaught Error: Loading non-context-aware native module in renderer:  '.../Release/iohook.node', but app.allowRendererProcessReuse is true,**
   as the error info mention above, I set app.allowRendererProcessReuse = false in main process, sadly
 the application process can't start again...

<img width="1315" alt="企业微信截图_b54a1ab4-71ed-4eae-9dc1-afea79b7d0f4" src="https://user-images.githubusercontent.com/3831666/95713767-b029ef80-0c99-11eb-8202-85f8ab5d9ffd.png">

I guess electron 10.1.1 is not supported by iohook currently?

**Comment by Djiit** [comment]
Hey, nope, still no official support. If you can help, it will be greatly appreciated. Closing this as we now state this in the README.
