### ISSUE TITLE
Cannot find module 'iohook' in Electron Production package

### ISSUE THREAD

**Issue by wuxiaoxiong** [wilix-team/iohook#257]
## Your Environment
* OS:  MacOS 10.15.6
* Node: v12.16.2
* Electron: v8.1.1
* package.json
```
"iohook": {
    "targets": [
      "node-72",
      "electron-76"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
"build": {
  "mac": {
      "extraFiles": [
        {
          "from": "node_modules/iohook/builds/electron-v76-darwin-x64/build/Release/iohook.node",
          "to": "./Resources"
        }
      ]
    }
}

"scripts": {
  "rebuildnew": "npm rebuild --runtime=electron --target=8.1.1 --disturl=https://atom.io/download/atom-shell --abi=76"
}
```

## Steps to Reproduce (for bugs)
1. `yarn run rebuildnew`
2. `electron-builder --mac --arm64` to pack for MacOS

## Context
`ioHook` work properly in dev mode, but alert error `Cannot find module 'iohook'` in production mode.

What should I do to resolve this problem?

**Comment by marcelblum** [comment]
There is no arm64 build of iohook. Are you really trying to package your app for unreleased Arm Macs or maybe you just made a mistake and meant to use `--x64`?

**Comment by ash0x0** [comment]
Closing as stale.
