### ISSUE TITLE
Lastest version of Electron and NodeJS with compatability

### ISSUE THREAD

**Issue by APIUM** [wilix-team/iohook#260]
I've been unable to get iohook working with any combination of Node and Electron that I have tried, what combinations are known working?

I hope this will serve as a reference to others like me who are looking to use this project.

**Comment by Djiit** [comment]
You are right. I added a bold statement in the README :

**PLEASE NOTE: The latest supported platform versions are Node 12 and Electrion 8. Want to help provide support for newer version ? Join the discussion [here](https://github.com/wilix-team/iohook/issues/241).**
