### ISSUE TITLE
ID for shortcuts is float numbers

### ISSUE THREAD

**Issue by lis355** [wilix-team/iohook#261]
In sources, i found this lines
```
shortcutId = Date.now() + Math.random();
...
shortcut.id === shortcutId
```

It means, what ids for shortcuts is a float numbers. I think, comparing 2 float numbers is very dangerous.
Yes, may be, in this library, you will not have situation, where you have 2 smooth equal float ids, but I worry about it.

**Comment by ash0x0** [comment]
Floating point comparison (and generally calculation) is all about error tolerance and precision. I think this is good enough for this particular use, it's only an issue in the most absolute theoretical sense.
