### ISSUE TITLE
Is the latest iohook compatible with electron 11?

### ISSUE THREAD

**Issue by PrinceKomali** [wilix-team/iohook#264]
I've been trying to make a nodejs alternative to Livesplit (a timer for speedruns) and I was looking into iohook for the global keypress stuff. However, I haven't gotten it to work so I did some searching and found that some electron versions weren't compatible. All I ask for is a simple answer: Is iohook (latest) compatible with electron 11? And if so, how do I set it up to make it work

* Node version: v12.16.3
* OS: Windows 10 64 Bit

**Comment by marcelblum** [comment]
Nope, check out the readme https://github.com/wilix-team/iohook#platform-support the latest supported Electron is 8.x. You could likely still do everything you want to do with iohook+Electron 8.

**Comment by PrinceKomali** [comment]
Thanks!
