### ISSUE TITLE
Develop a Desktop Application using Electron.JS with ioHook

### ISSUE THREAD

**Issue by gurpals** [wilix-team/iohook#280]
Running const ioHook = require(“iohook”); doesn’t work, even if that’s the only thing in the file

## Expected Behavior

Loads ioHook (get globally mouse & keypress counts in whole operating system)

## Current Behavior

White screen with this error in console.

## Steps to Reproduce (for bugs)

1. npm insall iohook - -save
2. npm start
3. When screen which is including iohook is opened, screen becomes blank and in console start showing this message.
4. When I remove const ioHook = require(“iohook”); error has gone, but ioHook not worked.
5. Package.json, ioHook included..

“iohook”: {
    “targets”: [
        “node-79”,
        “electron-85”
    ],
    “platforms”: [
        “linux”
    ],
    “arches”: [
        “x64”
    ]
}

## Context

1. Trying to implement keydown, mousedown event.
2. Trying to get mouse & keypress counts in whole OS.
2. Why doesn’t it work.

## Your Environment

Using:
Ubuntu 16.04 LTS
Node : v14.0.0
npm : 6.14.4
Electron : v11.1.1

![image](https://user-images.githubusercontent.com/10356059/103355935-90a2a600-4ad5-11eb-867f-ad13e783eae3.png)

**Comment by darkbox** [comment]
Facing same problem, didn't find a solution yet.
Ubuntu 20.04.1 LTS
Node: v10.19.0
Electron: 11.1.1
npm: 6.14.4

**Comment by ash0x0** [comment]
I'm not sure what the issue is. The information is not enough and I personally have it working fine under the same OS and runtime versions. Please reopen if this is still an issue and provide some more detail, a stacktrace would very much help.
