### ISSUE TITLE
Trying to use ioHook causes Electron to error.

### ISSUE THREAD

**Issue by MrDogeBro** [wilix-team/iohook#281]
## Expected Behavior

Once you install ioHook and add the required info into your package.json file, you should be able to require it in your main.js file and it should just work.

## Current Behavior

After installing ioHook abd adding required info into the package.json file, when electron is run it instantly errors that it can't find iohook.node.

Error:
```
Uncaught Exception:
Error: Cannot find module '.../node_modules/iohook/builds/electron-v85-darwin-x64/build/Release/iohook.node'
Require stack:
- '.../node_modules/iohook/index.js'
- '.../build/electron/main.js'
- '.../node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js'
```

Config in package.json
```json
"iohook": {
    "targets": [
      "node-72",
      "electron-85"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
```

## Steps to Reproduce (for bugs)

1. Install the package via npm
2. Add the configuration
3. Require the dependency in the main.js file of electron
4. Run the application - instantly pops up with the error and crashes the application

## Context

I am trying to detect all key presses while the application is open and in the background (not active).

## Your Environment

* Version used: 0.7.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node v12.16.3
* Operating System and version (desktop or mobile): OSX 10.11.6
* Electron version: 11.1.1

**Comment by MrDogeBro** [comment]
Ok, so it seems that when removing ia32 from the arches part of the ioHook config and then running npm install again, it seems to work. I did also upgrade my node version to the latest LTS (14.15.3) and updated the abi version for node in the package.json file. This is still a bug though. This doesn't make sense as to why this is happening.

**Comment by omiinaya** [comment]
> Ok, so it seems that when removing ia32 from the arches part of the ioHook config and then running npm install again, it seems to work. I did also upgrade my node version to the latest LTS (14.15.3) and updated the abi version for node in the package.json file. This is still a bug though. This doesn't make sense as to why this is happening.

could you explain what you mean by removing ia32 from config? i'm trying to reproduce those steps with no luck

**Comment by MrDogeBro** [comment]
> could you explain what you mean by removing ia32 from config? i'm trying to reproduce those steps with no luck

Removing the `ia32` option from the arches section of the iohook config in the package.json.

**Comment by omiinaya** [comment]
> > could you explain what you mean by removing ia32 from config? i'm trying to reproduce those steps with no luck
> 
> Removing the `ia32` option from the arches section of the iohook config in the package.json.

yeah, repeating the exact same thing wasn’t very helpful, but i did solve my issue by adding the following to my project’s package json: 

  "iohook": {
    "arches": [
      "x64",
      "ia32"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "targets": [
      "electron-85"
    ]
  }

and running npm rebuild after.

**Comment by ash0x0** [comment]
I believe this is resolved, seems to be a configuration error. Feel free to reopen if this is an issue that requires a fix.
