### ISSUE TITLE
Requiring the package crashes my script

### ISSUE THREAD

**Issue by Kale-Ko** [wilix-team/iohook#283]
# Requiring the package crashes my script

## Expected Behavior
It should run the lines after the require

## Current Behavior
It says this in the console and then exits and does not run a single line after the require

`refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 1 layouts.\
refresh_locale_list [493]: Received 1 locales.\
load_input_helper [866]: refresh_locale_list() found 1 locale(s).`

## Steps to Reproduce
1. Make a folder and install the package with `npm install iohook --save`
2. Create a file named index.js and type `const ioHook = require('iohook')` inside
3. Open a command prompt window and type node index.js

## Context
I am trying to make a node script that can move the mouse based on keyboard input (Don't ask why)

## Environment
* Package version: 0.7.2
* Node.js version: 15.3.0
* NPM version: 7.0.14
* OS: Windows 10 32 & 64 Bit
* Other Packages used: robotjs ^0.6.0
* Ran from the command prompt and powershell, same thing in both

**Comment by NeutronX-dev** [comment]
Happened to me. I installed the version `0.6.6`.
```
npm remove iohook
npm install iohook@0.6.6
```
and my code looks like this:
```js
const iohook = require('iohook');

iohook.on('keypress', (_key) => {
    let key = String.fromCharCode(_key.rawcode);
    console.log(key);
});

iohook.start();
```
Hope it Helps!

**Comment by Kale-Ko** [comment]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path node_modules\iohook
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! Downloading prebuild for platform: iohook-v0.6.6-node-v88-win32-x64
Downloading prebuild.tar.gz
npm ERR! Error: GET https://github.com/wilix-team/iohook/releases/download/v0.6.6/iohook-v0.6.6-node-v88-win32-x64.tar.gz returned 404
npm ERR! Prebuild for current platform (iohook-v0.6.6-node-v88-win32-x64) not found!
npm ERR! Try to compile for your platform:
npm ERR! # cd node_modules/iohook;
npm ERR! # npm run compile
npm ERR!
npm ERR!
npm ERR! node_modules\iohook\install.js:15
npm ERR!   throw err;
npm ERR!   ^
npm ERR! Prebuild for current platform (iohook-v0.6.6-node-v88-win32-x64) not found!
npm ERR! (Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by NeutronX-dev** [comment]
Then try with your previous version but add the `iohook.start();` line, maybe it isn't initializing.

**Comment by Kale-Ko** [comment]
It crashes when I require it, that will do nothing

**Comment by NeutronX-dev** [comment]
Try installing an older version

**Comment by marcelblum** [comment]
@Kale-Ko check this chart for the current state of platform support https://github.com/wilix-team/iohook/issues/268#issuecomment-751424507
Iohook v0.6.6 doesn't support node v15 but you could downgrade your node version to get it to work.

**Comment by Kale-Ko** [comment]
Ok, it works now! Thanks

**Comment by Eden4897** [comment]
I am using Node v14.15.3, and the same error happens to me. What version should I downgrade to?

**Comment by ash0x0** [comment]
Closing as solved, though this particular problem and solution will no longer be relevant after the next update.

**Comment by victorcid** [comment]
the problem keeps apering on the new vercion at lest with node 14

**Comment by ash0x0** [comment]
> the problem keeps apering on the new vercion at lest with node 14

Yeah the node 14 issue is unrelated and it's being tracked in other issues. If you really need this then you'd have to give up node 14.
