### ISSUE TITLE
Windows manual build

### ISSUE THREAD

**Issue by EnderArchery** [wilix-team/iohook#296]
## Context
Trying to package as dependency using nexe.

## Description
Using nexe, the .node module has to match the node version.
When it doesn't, you have to build it yourself, but the steps to do so are unclear.

1. When trying to use `npm rebuild iohook`, the error
  ```
  Prebuild for current platform (iohook-v0.6.6-node-v88-win32-x64) not found!
  Try to compile for your platform:
  # cd node_modules/iohook;
  # npm run compile
  ```
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;appears... which describes a wrong process, as the command should be `npm run build`

2. When building on windows it's necessary to install msys2 including `autotools`, `pkg-config`, `libtool`, `gcc`, `clang`, `glib` and `C++ Build Tools`
  Unfortunately there aren't any of those packages available. What are we meant to do?

## Your Environment

* Version used: 0.6.6
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 15.5.0 (v88)
* Operating System and version (desktop or mobile): Desktop, Windows

**Comment by WilixLead** [comment]
> npm run compile

Fixed few versions before

> Unfortunately there aren't any of those packages available

What do you mean? All this packages can be found in MinGW and other installers and google return well instructions

**Comment by ash0x0** [comment]
Closing. Feel free to reopen if you want support on this issue.
