### ISSUE TITLE
It seems there are two docs in parallel?

### ISSUE THREAD

**Issue by nick318** [wilix-team/iohook#301]
If we go to https://wilix-team.github.io/iohook/usage.html we will see targets:
```
"targets": [
    "node-59",
    "electron-57"
  ],
``` 
But in https://github.com/wilix-team/iohook/blob/master/docs/usage.md we can see:
```
"targets": [
    "node-72",
    "electron-85"
  ],
```

Seems first link leads to outdated docs, while there is an actual version.

**Comment by WilixLead** [comment]
Yes. It was fixed a few days ago. Closing it now
