### ISSUE TITLE
Using Iohook in Electron 12

### ISSUE THREAD

**Issue by Freihaut** [wilix-team/iohook#302]
I am trying to add iohook to my electron app, but can't get it to work.  I think the problem is that there is no prebuilt version for the most recent electron runtime.

I used electron-forge with webpack as the boilerplate for my app.
My Electron version ist: v12.0.1
My Node version ist: v14.16.0

Do you have any solution on how to (manually) add iohook to my app or do you have a timeline for support of the latest electron version? Excuse my question it it is nooby, I am a beginner and did not find any helpful instruction (for me) on how to use native node modules (e.g. I followed the instruction on https://www.electronjs.org/docs/tutorial/using-native-node-modules and ran .\node_modules\.bin\electron-rebuild.cmd after installing iohook with npm, but that did not work).

Thank you very much for any help!

**Comment by syamkp1986** [comment]
Got same problem with electron v 12.0.0.

**Comment by kiritnarain** [comment]
Same issue with 12.0.2

**Comment by joaomendoncaa** [comment]
Same issue with 12.0.2, does anyone know any alternative to iohook? (I'd like to capture key events out of the browser and terminal)

**Comment by WilixLead** [comment]
Guys. It all already documented here https://wilix-team.github.io/iohook/manual-build.html

**Comment by joaomendoncaa** [comment]
@WilixLead 
Thank you for the quick response!

Sorry, I'm having some trouble trying to understand the steps only by reading your documentation. 
I'm on Windows, node version: 14.15.5, electron version: 12.0.1.
I'm kind of new on this so I don't usually manually build packages. Where can I find more help on manually building the package?

**Comment by WilixLead** [comment]
Please wait today. I doing update for Electron v12. Should help you

**Comment by joaomendoncaa** [comment]
> 
> 
> Please wait today. I doing update for Electron v12. Should help you

Thanks a lot sir! Can you notify me whenever you make the update please? I can give you feedback on it!

**Comment by joaomendoncaa** [comment]
@WilixLead Good morning!

I saw you updated the package to electron version 12, but now I encountered a new problem. I get thrown an error saying:

Error: \\?\D:\myprojects\full-projects\bindbox\node_modules\iohook\builds\electron-v87-win32-x64\build\Release\iohook.node is not a win32 valid aplication.

Any ideas?

**Comment by WilixLead** [comment]
Done. Please check it. Closing issue for now, if something wrong just open it again
