### ISSUE TITLE
Signed electron app does not start with iohook on OSX (Unhandled Errpr: no suitable image found)

### ISSUE THREAD

**Issue by hemanth500apps** [wilix-team/iohook#303]
I have a signed and notarized App where I want to use iohook to simulate key taps. I had no problems building iohook locally but when I run it through the CI, where I sign and notarize the app, the app throws the following error upon starting:

## Current Behavior

![Screenshot-2021-03-17-at-4-38-51-PM](https://user-images.githubusercontent.com/49899639/111577717-d6b7fd80-87d8-11eb-8369-152d3d1c8ef1.png)

## Your Environment

* Version used: iohook 6.6
* Operating System and version (desktop or mobile):MacOS

**Comment by marcelblum** [comment]
Are you sure that error is due to iohook? It sounds like a code signing/certificate issue. I have successfully signed & notarized a macOS Electron app using iohook 0.6.6 without problems (packaged with Electron Forge).

**Comment by hemanth500apps** [comment]
> Are you sure that error is due to iohook? It sounds like a code signing/certificate issue. I have successfully signed & notarized a macOS Electron app using iohook 0.6.6 without problems (packaged with Electron Forge).

@marcelblum May I know the version of the electron and permission you are using.
i am using 
![image](https://user-images.githubusercontent.com/49899639/111579331-d66d3180-87db-11eb-9b95-6fdb595c3992.png)


I  removed IoHook, and build it , it's working fine

**Comment by WilixLead** [comment]
Check your builder settings and read the docs https://www.electronjs.org/docs/tutorial/using-native-node-modules
When your builder pack application it change or miss native module location, so you need check path after build

**Comment by ash0x0** [comment]
Closing as stale, and apparently answered. Feel free to reopen.
