### ISSUE TITLE
Some key down events don't occur when a lot of keys are already pressed.

### ISSUE THREAD

**Issue by jidagraphy** [wilix-team/iohook#304]
Im utilising iohook to make a musical instrument application.
When i hold down multiple keys (as if they are a music instrument), after 3 or more simultaneous keypress, any more keys are just ignored.

## Expected Behavior
I expect the key down events to occur even when ALL of the keys are pressed at the same time!

## Current Behavior
As explained above.

## Steps to Reproduce (for bugs)
1. any working example to log for keydown events
2. try pressing some combinations of keys down simultaneously. it only happens for some combinations. 
3. try for example, holding down Z B D and T, in order. no event for T key down. or A, L and O.

## Your Environment
Node.js 12.13.0, Chromium 80.0.3987.163, and Electron 8.5.5
MacOS 11.2.2

**Comment by jidagraphy** [comment]
So while typing that, i found out that this behavior is actually OS level behavior...
i.e. if you find any text box and try holding Z B D and T at the same time, T is not registered, unrelated to iohook...
I guess i could close this right now but could anyone throw any ideas on how i could tackle this?

**Comment by marcelblum** [comment]
It's not OS level, it's keyboard hardware level. This doesn't happen with a true "n-key rollover" keyboard which has unique switches for each key, a feature found in gaming keyboards or high end mechanical switch ones. Here's a good read on the deets from a co that makes nice NKRO keyboards (on which I'm typing right now) https://www.daskeyboard.com/blog/mechanical-keyboard-guide/

**Comment by jidagraphy** [comment]
#

> It's not OS level, it's keyboard hardware level. This doesn't happen with a true "n-key rollover" keyboard which has unique switches for each key, a feature found in gaming keyboards or high end mechanical switch ones. Here's a good read on the deets from a co that makes nice NKRO keyboards (on which I'm typing right now) https://www.daskeyboard.com/blog/mechanical-keyboard-guide/

Oh wow i did not expect that at all. that kind of renders my idea useless if I cant use a typical macbook keyboard. Thanks, nonetheless!
