### ISSUE TITLE
Using iohook with React and Electron

### ISSUE THREAD

**Issue by andremonteiro95** [wilix-team/iohook#305]
I am not able to use iohook with React and Electron on the renderer process. 
I tried to use it in the main process but the app crashes when I click certain keys, e.g. the caps lock key.
According to #244 and #246, the problem is solved after importing iohook in the renderer process. Now, I use React, webpack and electron-builder. I get the following error: 

> Cannot find module '/builds/electron-v80-darwin-x64/build/Release/iohook.node'.

I tried to change the source code to statically import that file, and I got the following error: 

> TypeError: NodeHookAddon.startHook is not a function

Has anyone been successful using iohook with React and Electron?

**Comment by visgotti** [comment]
5 days and nothing? :( having the same issue but with vue.

**Comment by WilixLead** [comment]
It is not fully related to iohook. Issue with your builders (electron-builder or webpack config), so you need check your application directory (or asar file) that should have path like '/builds/electron-v80-darwin-x64/build/Release' with iohook.node file. 
And read this docs https://www.electronjs.org/docs/tutorial/using-native-node-modules
