### ISSUE TITLE
Cannot find module for electron(build failed)

### ISSUE THREAD

**Issue by programerr01** [wilix-team/iohook#306]
I tried running iohook with electron application, basic example but it is giving error  
```
node:103385) UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/linux/Electron/database/node_modules/iohook/builds/electron-v87-linux-x64/build/Release/iohook.node
```
**I checked the build folder it contains build for node but not for electron**

## Possible Solution
any way to build it for electron

##  Environment

* Version used:0.6.6
* node: v14.16.0
* npm: 6.14.11

**Comment by programerr01** [comment]
##  I used Version 4.1.4 for electron. It solved the issue

**Comment by eyesmarty** [comment]
electron Version 4.1.4 is very old as current version is 11? is there any other possible solution
