### ISSUE TITLE
iohook install script not working

### ISSUE THREAD

**Issue by PiggyPlex** [wilix-team/iohook#318]
## Expected Behavior

iohook installs

## Current Behavior

iohook not install; install script fails
```
C:\a\Development\Minecraft\Client>npm i iohook -S
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\a\Development\Minecraft\Client\node_modules\iohook
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Downloading prebuild for platform: iohook-v0.9.1-node-v88-win32-x64
Downloading prebuild.tar.gz
npm ERR! Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v88-win32-x64.tar.gz returned 404
npm ERR! Prebuild for current platform (iohook-v0.9.1-node-v88-win32-x64) not found! 
npm ERR! Try to build for your platform manually:
npm ERR! # cd node_modules/iohook;
npm ERR! # npm run build
npm ERR!
npm ERR! C:\a\Development\Minecraft\Client\node_modules\iohook\install.js:16        
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, open 'C:\Users\aideo\AppData\Local\Temp\prebuild.tar.gz'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\a\\AppData\\Local\\Temp\\prebuild.tar.gz'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\a\AppData\Local\npm-cache\_logs\2021-04-19T20_40_14_549Z-debug.log
```

## Steps to Reproduce (for bugs)

1. Run `npm i iohook -S`

## Context

Installing iohook

## Your Environment

* Version used:
* Latest
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Latest
* Operating System and version (desktop or mobile):
* Desktop, Windows 10
* Link to your project:

**Comment by catdad** [comment]
The latest `v0.9.1` tag published this morning does not include any of the Windows prebuilds. I think the appveyor builds just need to be rerun?

Interesting, the `undefined0.9.1` tag does include Windows, Linux, and Mac prebuilds, but of course that is not the one used for downloads. I am not sure why there are two to three tags created per version, but I am happy to help fix that if someone has any clues.

**Comment by Palerion** [comment]
I've run into this issue as well; exact same errors as the OP. I'm not especially experienced with app development yet, but I've been building a tool that could really use iohook's functionality. Might there be a way to get around this issue until it's resolved?

**Comment by WilixLead** [comment]
Yes, I found bug related to install script after publishing update. At this moment you can use older versions 0.9.0 or 0.8.x.
Today I try fix this problem

**Comment by Palerion** [comment]
Not sure if I should create a new issue for this or if it's fine to address it here, I'm getting "Uncaught Error: Cannot find module 'iohook'" after attempting to run my application with iohook v0.9.0 installed. I've checked node_modules and iohook is certainly there, so I'm quite baffled by this issue. 
![image](https://user-images.githubusercontent.com/49882826/115417704-d68b9300-a1c6-11eb-9ec1-876766ed2ab5.png)

**Comment by renzner** [comment]
> Not sure if I should create a new issue for this or if it's fine to address it here, I'm getting "Uncaught Error: Cannot find module 'iohook'" after attempting to run my application with iohook v0.9.0 installed. I've checked node_modules and iohook is certainly there, so I'm quite baffled by this issue.
> ![image](https://user-images.githubusercontent.com/49882826/115417704-d68b9300-a1c6-11eb-9ec1-876766ed2ab5.png)

Make sure the iohook is not on devDependencies. Also on the latest iohook, if you package your app (I used electron-packager) and use the asar option, you need to exclude files with certain extentions. I didn't do that on the old version of iohook.

`asar: {
		unpack: '*.{node,dll,so,dylib}',
},`

Hope this helps.

**Comment by ash0x0** [comment]
refer to #335. @renzner thanks for the info on packager builds, will include that in docs.
