### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by perfectwebtech** [wilix-team/iohook#321]
hello

widnows 10 does not work 

anybody can help or any suggestion for install in windows 10 

or runtime something ?

**Comment by IvanGodinez21** [comment]
> hello
> 
> widnows 10 does not work
> 
> anybody can help or any suggestion for install in windows 10
> 
> or runtime something ?

Hello, remember to install [Node.js](https://nodejs.org/es/)
Then in the console you have to install the last version of iohook using:
```
npm i iohook
```
If the console throw errors try installing other version, I'm currently using 0.6.6
```
npm i iohook@0.6.6
```
Then you can test iohook using the next example
```
const ioHook = require('iohook');
ioHook.on('keydown', event => {
    console.log(event);
});
ioHook.start();
```
And finally run the javascript file using this in the console
```
node file.js
```

**Comment by perfectwebtech** [comment]
thanks a lot in morning i will try but similar version will work in mac windows all version and linux all version too right ?

**Comment by ash0x0** [comment]
refer to #335
