### ISSUE TITLE
Missing pre-builds for win32 in last release (v0.9.1) ?

### ISSUE THREAD

**Issue by Seblor** [wilix-team/iohook#322]
I took a look at the release from the last week and saw the 2 tags, one being "undefined0.9.1", which I guess is an issue, leading to the "v0.9.1" release. However, that second release is missing the win32 binaries that are present in the "undefined0.9.1" release. Is this a mistake ?

**Comment by sujiewen** [comment]
node 83 win32 x64
Downloading prebuild for platform: iohook-v0.9.1-node-v83-win32-x64
Downloading prebuild.tar.gz
Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v83-win32-x64.tar.gz returned 404
Prebuild for current platform (iohook-v0.9.1-node-v83-win32-x64) not found!
Try to build for your platform manually:
# cd node_modules/iohook;
# npm run build

**Comment by sujiewen** [comment]
Is this the reason?
=================================================

node 83 win32 x64
Downloading prebuild for platform: iohook-v0.9.1-node-v83-win32-x64
Downloading prebuild.tar.gz
Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v83-win32-x64.tar.gz returned 404
Prebuild for current platform (iohook-v0.9.1-node-v83-win32-x64) not found!
Try to build for your platform manually:
# cd node_modules/iohook;
# npm run build

**Comment by Seblor** [comment]
I made this issue to point out the fact that the win32 binaries in the "undefined0.9.1" release could be included in the "v0.9.1" release.

On a side note, I have completly given up on building this module from source as I have already lost days trying to make it work.

**Comment by llermaly** [comment]
bump, pls help

**Comment by ash0x0** [comment]
refer to #335
