### ISSUE TITLE
Iohook install on windows 10 64 doesn't work 

### ISSUE THREAD

**Issue by rvie17** [wilix-team/iohook#325]
I'm kind of a newbie in js. 
I have run 'npm i iohook ' to install iohook and it exit with EXIT 1 status. 
and the following code : 
> node install.js

Can't resolve main package.json file
Downloading prebuild for platform: iohook-v0.9.1-node-v79-win32-x64
Downloading prebuild.tar.gz
Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v79-win32-x64.tar.gz returned 404
Prebuild for current platform (iohook-v0.9.1-node-v79-win32-x64) not found!
Try to build for your platform manually:
# cd node_modules/iohook;
# npm run build

C:\Users\kite g17\Google Drive\javascript\node_modules\iohook\install.js:16
  throw err;
  ^

[Error: ENOENT: no such file or directory, open 'C:\Users\KITEG1~1\AppData\Local\Temp\prebuild.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\KITEG1~1\\AppData\\Local\\Temp\\prebuild.tar.gz'
}
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\kite g17\Google Drive\javascript\package.json'
npm WARN javascript No description
npm WARN javascript No repository field.
npm WARN javascript No README data
npm WARN javascript No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.9.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kite g17\AppData\Roaming\npm-cache\_logs\2021-05-08T09_13_05_964Z-debug.log

I think he just can't reach the right file because of the 404 error. 
Hope someone would help :)

**Comment by ddavisj** [comment]
Any progress? Keen to try this out but getting the same error..

**Comment by ShikyohRay** [comment]
The release download address has an 'undefined'.And the download address is like this:
```
  let downloadUrl = 'https://github.com/wilix-team/iohook/releases/download/v' + pkgVersion + '/' + currentPlatform + '.tar.gz';
```
Change a version may fix this problem.

**Comment by ash0x0** [comment]
refer to #335

**Comment by talksik** [comment]
something that was important for me was to add iohook to nohoist if you are using yarn workspaces
