### ISSUE TITLE
iohook .node is not a valid win32 application

### ISSUE THREAD

**Issue by Kamran95** [wilix-team/iohook#328]
### Package JSON Node ABI
  "iohook": {
    "targets": [
      "node-75",
      "electron-85"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
### Error
resources\app.asar.unpacked\node_modules\iohook\builds\electron-v80-win32-x64\build\Release\iohook.node is not a valid Win32 application.
\?\C:\Users\Financials Unlimited\AppData\Local\Programs\eyesmarty\resources\app.asar.unpacked\node_modules\iohook\builds\electron-v80-win32-x64\build\Release\iohook.node
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034)
    at Object.func [as .node] (electron/js2c/asar.js:149)
    at Module.load (internal/modules/cjs/loader.js:815)
    at Module._load (internal/modules/cjs/loader.js:727)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:852)
    at require (internal/modules/cjs/helpers.js:74)
    at Object.<anonymous> (C:\Users\Financials Unlimited\AppData\Local\Programs\eyesmarty\resources\app.asar\node_modules\iohook\index.js:10)
    at Object.<anonymous> (C:\Users\Financials Unlimited\AppData\Local\Programs\eyesmarty\resources\app.asar\node_modules\iohook\index.js:397)

**Comment by eyesmarty** [comment]
facing same issue any progress with the solution
?

**Comment by eyesmarty** [comment]
@WilixLead ?

**Comment by italodeandra** [comment]
I'm also looking for a fix for this.

The workaround is to manually download the build from here https://github.com/wilix-team/iohook/releases/tag/undefined0.9.1

The one you're looking for is https://github.com/wilix-team/iohook/releases/download/undefined0.9.1/iohook-v0.9.1-electron-v80-win32-x64.tar.gz

You need to extract it in the folder the application is looking for it, which in your case is `resources\app.asar.unpacked\node_modules\iohook\builds\electron-v80-win32-x64`.

**Comment by nilkamal-bahaji** [comment]
Getting the same error - "\node_modules\iohook\builds\electron-v87-win32-x64\build\Release\iohook.node is not a valid Win32 application.". Also tried what @italodeandra mentioned. Downloaded and extracted the build folder. Then after running the app I'm getting  - 

"Error: The module '..\..\node_modules\iohook\builds\electron-v87-win32-x64\build\Release\iohook.node'
was compiled against a different Node.js version using 
NODE_MODULE_VERSION 80. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing."

Any other solution???

**Comment by italodeandra** [comment]
That's a different issue and seems weird. Did you download the version 87 from the [this](https://github.com/wilix-team/iohook/releases/tag/undefined0.9.1) link? If yes, I suggest downgrading your Node.js version and trying again (it will probably ask you to install a different version).

**Comment by ash0x0** [comment]
This is a current issue with `v0.9.1` release. For windows install `v0.9.0` and for linux and mac you can use `v0.9.1`. Will resolve very soon.

**Comment by italodeandra** [comment]
Still not fixed even on `v0.9.2`. What is the recommended environment?

**Comment by italodeandra** [comment]
My previous workaround is not working anymore. It seems you removed the release I was using to download the build. 😢

**Comment by ash0x0** [comment]
@italodeandra sorry for delay here. It should download the correct build if you have the correct config in your package. Share your config, it's probably the case that you're using an electron/node combination that's not build.

**Comment by italodeandra** [comment]
@ash0x0 It's working fine now. Thanks!
