### ISSUE TITLE
Version 0.9.1 Installation issues

### ISSUE THREAD

**Issue by ash0x0** [wilix-team/iohook#335]
If you're having issues installing `iohook@0.9.1` please be informed that currently there is no prebuild available for this version for windows, only for linux and mac. The workaround is to use `iohook@0.9.0` for windows and `iohook@0.9.1` on linux and mac.

**UPDATE**: Installing any version should now work on all platforms, **including v0.9.0 and v0.9.1**, which can now be installed on all three platforms just like any other version.

**Comment by Seblor** [comment]
This is confusing.

If there are no win32 builds for 0.9.1, why are there win32 builds in the tag `undefined0.9.1` ?

And why is the tag `undefined0.9.1` flagged as latest release instead of `v0.9.1` which only has the darwin & linux releases ?

**Comment by ash0x0** [comment]
> This is confusing.
> 
> If there are no win32 builds for 0.9.1, why are there win32 builds in the tag `undefined0.9.1` ?
> 
> And why is the tag `undefined0.9.1` flagged as latest release instead of `v0.9.1` which only has the darwin & linux releases ?

This is an issue with the current build system. The install script doesn't see the `undefined0.9.1` tag therefore it doesn't find a `win32` build. This will be fixed through a change to CI and the build script as soon as I'm done cleaning up issues and PRs.

**Comment by robbylucia** [comment]
@ash0x0 
Thank you for your work along with let-value and the original maintainer. I look forward to the new Windows version

**Comment by ash0x0** [comment]
This issue should be fixed in version 0.9.2 just published. Whoever can confirm please do so we can close.
This issue is not happening anymore in my testing on all three platforms with node 14 and electron 11. Please report if there are any issues experienced related to this.

**Comment by marcelblum** [comment]
@ash0x0 tested working on Win 10 / Electron 12. Thanks much for your efforts!

**Comment by ash0x0** [comment]
Great. `v0.9.0` and `v0.9.1` releases have been fixed as well so any installation issues specific to these two releases won't happen anymore.
There will be no need to keep this issue open or pinned as soon as I have confirmed this on all platforms.

**Comment by ash0x0** [comment]
There have been enough new downloads in the last 2 days that I'm comfortable closing this now. Will remain pinned for a week if anyone wants to reopen.

**Comment by vickylance** [comment]
Any reason why this is still pinned issue I think its safe to unpin
