### ISSUE TITLE
SIGSEGV on mac catalina 10.15.6

### ISSUE THREAD

**Issue by abacaj** [wilix-team/iohook#338]
Before exiting electron (app.quit) I unload iohook and still get a SIGSEGV.

Even if I don't use iohook, just a simple require('iohook') and app.quit will cause a SIGSEGV.
I tried the last 3 builds of iohook and all have the same issue. Electron 87.

Referencing #250 as it's a similar issue.
Mac stack:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by ash0x0** [comment]
Closing as duplicate. Let's keep it there.
