### ISSUE TITLE
iohook.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by Grayseon** [wilix-team/iohook#345]
(This is my first issue on GitHub, so sorry if I don't give enough detail)

When using IOhook with Electron, it gives me an error:
iohook.node is not a valid Win32 application.

## Expected Behavior

When running the application, it should output something when I press a key, or move the mouse.

## Current Behavior

It errors when I only require IOhook in my index.js

## Steps to Reproduce (for bugs)

1. Install electron, and IOhook
2. Require IOhook in the index.js
3. Run the script with npm start (in package.json the start script runs electron . )

## Context

I'm making an application where you can share mice between Windows and Mac computers.

## Your Environment

- IOHook Version: 0.9.3
- Environment name and version: v12.18.4
- Operating System and version: Windows 10 desktop x64
- Modules: IOhook, RobotJS, Electron, ws, electron-rebuild

## Things that I have tried

#328 
#320 
https://www.electronjs.org/docs/tutorial/using-native-node-modules#using-native-node-modules

**Comment by ash0x0** [comment]
Make sure to follow [usage guide](https://wilix-team.github.io/iohook/usage.html#electron). I suspect you don't have the proper config for iohook in your `package.json`. If that's not the case, please share your entry in `package.json` and a full stack trace of the error.

**Comment by Grayseon** [comment]
For my IOhook entry it's:

"iohook": {
    "targets": [
      "node-72",
      "electron-89"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }

**Comment by ash0x0** [comment]
Can you provide a full stack trace? Also, are you using electron version 10?

**Comment by Grayseon** [comment]
![image](https://user-images.githubusercontent.com/86214551/125136692-f00aef80-e0d0-11eb-9894-994e4e367737.png)

Also I'm using Electron v13.1.6

**Comment by ash0x0** [comment]
Electron 13 isn't supported yet because it has new requirements for native modules. That's why it's not working for you. When this is fixed I'll update here but for now you can use electron 12 or use an alternative library for your os.

**Comment by Grayseon** [comment]
Thank you for your help!
