### ISSUE TITLE
manual build iohook failed with gyp stack error

### ISSUE THREAD

**Issue by alexxxcs1** [wilix-team/iohook#351]
try manual build iohook , but build failed with error

```
make: *** No rule to make target `Release/obj.target/uiohook/libuiohook/src/logger.o', needed by `Release/uiohook.dylib'.  Stop.
```
i see this error is fixed [https://github.com/wilix-team/iohook/pull/258#issuecomment-723083004](url) 

but it not look like not work ?

## Expected Behavior

build success

## Current Behavior

throw error

## Your Environment

- IOHook Version: v0.9.3
- Environment name and version (e.g. Chrome 39, node.js 5.4, electron 11.2): node v12.14.1, electron runtime node version v12.16.3, electron v10.4.7
- Operating System and version (desktop or mobile): desktop macos v11.2.2
- Optional Link to your project:local
- package.json iohook config 
```
"iohook": {
    "targets": [
      "node-72",  //this version is current mac installed node version abi or electron runtime's node version abi ? it has diffrence
      "electron-50"
    ],
    "platforms": [
      "darwin"
    ],
    "arches": [
      "x64"
    ]
  }
```

**Comment by sp0033212000** [comment]
Hi, have you solved the problem yet?
