### ISSUE TITLE
Can't install iohook

### ISSUE THREAD

**Issue by ninetyeights** [wilix-team/iohook#364]
OS Version: macOS 11.6
Node Version: v16.9.1
Electron Version: v14.0.0
iohook Version: v0.9.3

Error:
npm install iohook --save

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/$USER/tmp/testing/node_modules/iohook
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Downloading prebuild for platform: iohook-v0.9.3-node-v93-darwin-x64
Downloading prebuild.tar.gz
npm ERR! Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.3/iohook-v0.9.3-node-v93-darwin-x64.tar.gz returned 404
npm ERR! Prebuild for current platform (iohook-v0.9.3-node-v93-darwin-x64) not found!
npm ERR! Try to build for your platform manually:
npm ERR! # cd node_modules/iohook;
npm ERR! # npm run build
npm ERR!
npm ERR! /Users/$USER/tmp/testing/node_modules/iohook/install.js:16
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, open '/var/folders/8v/hcm_f2j95pvck6wktnb74rnw0000gn/T/prebuild.tar.gz'] {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'open',
npm ERR!   path: '/var/folders/8v/hcm_f2j95pvck6wktnb74rnw0000gn/T/prebuild.tar.gz'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/$USER/.npm/_logs/2021-09-26T16_25_56_774Z-debug.log

**Comment by yummyweb** [comment]
Hi I have been struggling with this issue for the past few hours and I followed this solution in order to fix my issue:
https://github.com/1kc/razer-macos/issues/289#issuecomment-799272929

**Comment by marcelblum** [comment]
There is no prebuild available for Electron 14 yet, but you can compile it manually. Tested working on macOS 11.6 x64.

**Comment by leizelong** [comment]
see the issure https://github.com/wilix-team/iohook/issues/391
