### ISSUE TITLE
Module could not be found when app is packaged in asar

### ISSUE THREAD

**Issue by jove0610** [wilix-team/iohook#396]
The error appears when I packaged the app as asar. There is no error during the packaging and it will package successfully, only when I open the application I got the error. The error will not appear and the app will open normally if I did not package it as asar.

## Expected Behavior
App will work when I packaged an app as asar.

## Current Behavior
Here is the error:
![error](https://user-images.githubusercontent.com/39666463/161365284-8b087de2-6f65-4768-925e-bcf8562a24cb.png)

I can only get the image of the error. I can't copy-paste the text.

## Steps to Reproduce (for bugs)

1. Install electron-forge boilerplate `npx create-electron-app@latest my-app`
2. Downgrade to electron@17
3. Install iohook, write console.logs in index.js to test iohook.
4. Enable asar during packaging in package.json:
```
"config": {
    "forge": {
      "packagerConfig": {
        "asar": true
      },
      // maker config
    }
  },
```

## Context
I am trying to package my app in asar file, I read in electron docs that it optimizes the app. Also, it'll look more professional if the app is in asar.

## Your Environment
- IOHook Version: 0.9.3
- Environment name and version: electron v17.3.1 and node v14.9.1
- Operating System and version (desktop or mobile): Windows 10
- Optional Link to your project:

Thanks

**Comment by marcelblum** [comment]
Best to exclude the iohook binaries (and any other native module binaries you might be using) from the asar. Adding this option to `packagerConfig` covers most cases:
```
packagerConfig: {
	asar: {
		unpack: "**/*.+(node|dll|exe)",
		smartUnpack: true
	}
}
```

**Comment by jove0610** [comment]
Thanks @marcelblum
