### ISSUE TITLE
Cannot find module iohook.node

### ISSUE THREAD

**Issue by dmatora** [wilix-team/iohook#414]
This has been asked many times (particularly #359 #349 #182 #55), but I can't see answers to this
App works in development mode (yarn start) but when extracted from production package throws exception
```
Uncaught Exception: Error: Cannot find module App.app/Contents/Resources/app.asar/dist/main/builds/electron-v103-darwin-x64/build/Release/iohook.node' at t (App.app/Contents/Resources/app.asar/dist/main/main.js:2:637385) at Object.1756 (App.app/Contents/Resources/app.asar/dist/main/main.js:2:634104)
```
Even after replacing
```
    "package": "ts-node ./.erb/scripts/clean.js dist && npm run build && electron-builder build --publish never",
```
by
```
    "package": "ts-node ./.erb/scripts/clean.js dist && npm run build && cp -r node_modules/iohook/builds release/app/dist/main && electron-builder build --publish never",
```
I get same error, even seeing that `/Applications/App.app/Contents/Resources/app.asar.unpacked/dist/main/builds/electron-v103-darwin-x64/build/Release/iohook.node` does present

When I set "asar" to false in packages json, I can see 
`/Applications/App.app/Contents/Resources/app/dist/main/builds/electron-v103-darwin-x64/build/Release/iohook.node` does present, but still get 
```
Uncaught Exception:
Error: Cannot find module '/Applications/App.app/Contents/Resources/app/dist/main/builds/electron-v103-darwin-x64/build/Release/iohook.node'
at t (/Applications/App.app/Contents/Resources/app/dist/main/main.js:2:255240)
```

Solved by adding iohook not just to /package.json but also to /release/app/package.json

**Comment by devRitik** [comment]
@dmatora I am facing the same issue on mac m1. I am not able to find /release/app/package.json file or folder in my project. Please check

**Comment by chen-shuaige** [comment]
Unable to understand /release/app/package.json, where is it
