### ISSUE TITLE
(chore) Add tests

### ISSUE THREAD

**Issue by Djiit** [wilix-team/iohook#51]
We should include at leasts some tests to ensure every push to `master` is fine.

**Comment by matthewshirley** [comment]
Scoped this out with Jest and RobotJS.

```
const ioHook = require('./index')
const robot = require("robotjs");

// The assertion for a promise must be returned.
it('receives the text "Hello World"', async (done) => {
    let currentKey = 0;

    const actualCharacters = [];
    const expectedChracters = ['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd'];
    
    const eventCallback = (event) => {
        actualCharacters.push(String.fromCharCode(event.keychar))
        
        if (currentKey === expectedChracters.length) {
            expect(actualCharacters).toEqual(expectedChracters);
        }

        currentKey += 1;
        done();
    };

    ioHook.on('keypress', eventCallback);
    ioHook.start()

    robot.typeString("Hello World");
});
```

**Comment by Djiit** [comment]
This is great! Do you want to put this in a PR? Currently merging all the existing ones. Thanks !

**Comment by matthewshirley** [comment]
Let's write a test for the shortcuts and maybe test the mouse.

**Comment by Djiit** [comment]
@DCzajkowski it seems that the test are not passing on CI https://travis-ci.org/WilixLead/iohook/jobs/378076504

**Comment by DCzajkowski** [comment]
Not really. BUT, I have hard time building the whole thing because of version mismatches etc. I don't think it's my code that broke anything, because I have not touched anything regarding builds... So I have no clue what causes Travis to fail

**Comment by Djiit** [comment]
Actually it is the tests not passing :). I think I will silence them for now.

**Comment by DCzajkowski** [comment]
Ehh... Do you know how to fix them?

**Comment by DCzajkowski** [comment]
This could help: https://github.com/facebook/jest/issues/5123

**Comment by ash0x0** [comment]
Closing as stale.
