### ISSUE TITLE
key down do not capture keychar. reason?

### ISSUE THREAD

**Issue by adamchenwei** [wilix-team/iohook#54]
here is what I got when capture event for `keydown` when I keydown on `f`

`{"keycode":33,"rawcode":3,"type":"keydown"}`

latest iohook
MacOS High Sierra
Node 8.9.1

**Comment by Djiit** [comment]
Hi, can you try with keyup ?

**Comment by adamchenwei** [comment]
@Djiit  nop. still no keychar. Is it removed in certain version, accidentally?

**Comment by Djiit** [comment]
According to #1 , it might be normal as `keychar` is only present in the `keypress` event.

**Comment by adamchenwei** [comment]
@Djiit `keypress (NOT WORKING AT THIS MOMENT, USE keydown/keyup)` it says in doc.. and yes, its not working I just confirmed, it just stuck, not showing any log

**Comment by JanUnld** [comment]
Just to get you moving if you're hardstuck on this issue. Your can use `String.fromCharCode()` at any time.

```javascript
ioHook.on("keydown", e => {
  console.log(e.rawcode, String.fromCharCode(e.rawcode));
})

// Outputs something like:
// 69 "E"
```

This is of course just a low level solution since this doesn't consider things like localization or lower-/uppercase. But I still hope this does fit in your case... 😊

**Comment by Djiit** [comment]
Nice workaround ! I'll put it in the readme too in a "Tips" section.

**Comment by adamchenwei** [comment]
I haven't close this issue just in case you all want this ticket to be used as a follow up otherwise feel free to close it!

**Comment by Djiit** [comment]
You're welcome @adamchenwei ! I'll close this when the doc will be updated.

**Comment by adamchenwei** [comment]
@JanUnld @Djiit just verified the work around a bit, but seems not really working correctly.
I am on MacOS High Seirra

console log the keydown event watch, what I got for a keydown on `a` key, I got
`0 '\u0000'`

but in the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode

I see 

`String.fromCharCode(65);
"A"`

maybe some clarification? Still new to this sort of low-level code
 stuff hehe

**Comment by Djiit** [comment]
You are right. According to https://github.com/WilixLead/iohook/issues/18 (note: I learnt a lot of thing digging into old issues :)), the keycodes are the one issued by libuiohook (Linux). So we might craft some sort of lookup table.

**Comment by adamchenwei** [comment]
awesome! looking forward for the fix. this is pretty critical piece, really looking forward for the fix! 👍

**Comment by Djiit** [comment]
A bit more info : these keycodes are based on en-US standard keyboard so they are related to the "location" of keys on your keyboard... Sounds harder than expected.

**Comment by adamchenwei** [comment]
btw, I saw this table http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlkeycodes.html

is that whats really it? some sort of mapping between what I see in the iohook to the key listed in the first left column?

**Comment by Djiit** [comment]
Yep, only if you use a standard QWERTY keyboard

**Comment by adamchenwei** [comment]
not really sure what does that mean.... can't we just show warning if someone using non standard keyboard? I mean seems another set DVORAK, nicer layout but almost below 1% is using them approx..... https://www.quora.com/What-percent-of-the-population-uses-Dvorak\

It can be  realllllly awesome to have this feature in to take care of 99% of us and maybe improve and iterate?

**Comment by adamchenwei** [comment]
i would have just make a javascript matcher lol but I guess its not very performant for this purpose. since seems everything is built with... other programming language...

**Comment by Djiit** [comment]
It could work actually. Make a JS object with the good key/value pairs form the table above and wrap it in a function like `keycodeToChar(keycode)`. We'll add it to the README for general use at first, and we could then discuss if it fits in this project (in the iohook object maybe ? to use it only when to want with e.g. `iohook.keycodeToChar(e.keycode)`.

**Comment by adamchenwei** [comment]
that sounds good!

**Comment by adamchenwei** [comment]
but, one thing though, seems its still can't recognize cap though ha.....

**Comment by Djiit** [comment]
I don't think so. Speaking of hardware/input, this is the same key :/ I think you can detect Shifted key, but capslocked key could be harder.

**Comment by adamchenwei** [comment]
hum, ok, that's interesting though on that. I can build a small key matching file. let see how it goes~ thanks, lets keep updated.

**Comment by matthewshirley** [comment]
This is how libuiohook displays key events:

![capture](https://user-images.githubusercontent.com/450704/38635260-ab169e5e-3d79-11e8-86f1-395a9539cad8.PNG)

We can add the character to the keypress event but keyup and keydown will always be the upper case character.

**Comment by matthewshirley** [comment]
@adamchenwei I'm working on that now. See #61

**Comment by matthewshirley** [comment]
Sorry, I'm still learning my way around the code. I noticed that the mask value actually represents the modifier values... 0x1 is shift. I'll expose this in the event object.

**Comment by matthewshirley** [comment]
@pitops I don't believe so. I think this would require implementation by libuiohook.

You could:
- Use the mask to track if the user has pressed capslock previously (mask 0x4000)
- Listen to the 'keypress' event and if there is no shift mask and the keychar is capital... assume it's a capslock.

**Comment by vielhuber** [comment]
As of today, we are unable to get the actual char pressed. Is this correct?

In the meantime: Are there other node solutions where you can fetch the pressed input chars?

**Comment by Djiit** [comment]
Indeed this is directly linked to libuiohook not capturing CAPS_LOCK. Closing this for now.
