### ISSUE TITLE
(discuss) migrating this repository and publishing new versions

### ISSUE THREAD

**Issue by Djiit** [wilix-team/iohook#57]
Hi guys,

Just a word here to tell you i'm thinking of forking once-and-for-all this repository.

I'm having a hard time contacting @WilixLead and I can't get the right permissions to : 
1. give us some nice-to-have-tools in this repository
2. deploy newer, better version on NPM.

I'm considering moving the repository and creating a new package name (no ideas yet, but a derivative of iohook).

Any ideas on this ?

**Comment by matthewshirley** [comment]
I'd love to see a gitter.im created and some defined goals for development. 👍

**Comment by Djiit** [comment]
@WilixLead , any thought ? I can't go further without admin/owner rights. Thanks !

**Comment by Djiit** [comment]
Closing this as we are now under an organization, allowing more flexibility and tools !
