### ISSUE TITLE
Add some style guide

### ISSUE THREAD

**Issue by DCzajkowski** [wilix-team/iohook#82]
I think we should add a style guide to this repo, by using eslint + prettier. I am unsure what the current intent is, so I can't really make a PR with the configuration — as it depends on creators' taste.

Useful link: https://www.youtube.com/watch?v=YIvjKId9m2c

**Comment by Djiit** [comment]
Hi there, we should have a look to https://github.com/xojs/xo

**Comment by ash0x0** [comment]
Will add this soon.

**Comment by ash0x0** [comment]
Style guide is done. Using `eslint` for linting with `prettier` style. Added to package and `husky` hooks.
