### ISSUE TITLE
Media Keys support

### ISSUE THREAD

**Issue by danieldaeschle** [wilix-team/iohook#87]
If i press a media key like MediaNextTrack the keycode is 0. Is there a iohook.on('mediakeynext') ??

**Comment by DCzajkowski** [comment]
There is nothing like this and current implementation doesn't support it.

Something to bare in mind: https://stackoverflow.com/questions/26280582/keyboard-media-key-strokes-impossible-to-capture. 

Although it seems like jnativehook can handle that, so maybe it is possible... https://github.com/kwhat/jnativehook/issues/83

PRs are welcome ;)

**Comment by danieldaeschle** [comment]
I need JS not java :D

electron has native support for that. But it doesn't work with mate and gnome

**Comment by DCzajkowski** [comment]
I understand that. I was just saying that if jnativehook can handle it, iohook technically could too. But it's currently not supported.
You could also give [GKM](https://github.com/tomzx/gkm) a try. But it requires having Java installed, so if you are making an Electron app, it won't really work for you.

**Comment by ash0x0** [comment]
This will probably never be supported. It could at the very most be supported at keycode level but not mapped.
