### ISSUE TITLE
Segfault in production mode

### ISSUE THREAD

**Issue by anhang** [wilix-team/iohook#92]
## Expected Behavior
iohook works great in dev mode, but after i compile with `electron-builder`, the resulting .exe crashes
Then, dev mode starts crashing. Deleting my `node_modules` folder will get dev mode to work again.

## Steps to Reproduce (for bugs)
1. compile an example electron project with `electron-builder` with the following config:
```
  "build": {
    "productName": "ABC",
    "appId": "com.ABC",
    "win": {
      "publisherName": "ABC",
      "target": "nsis"
    },
    "files": [
      "**/*",
      "build/icon.*"
    ],
    "asar": true,
    "nsis": {
      "oneClick": true,
      "allowToChangeInstallationDirectory": false,
      "perMachine": true,
      "artifactName": "${productName} Installer ${version}.${ext}"
    }
  },
```

2. Run `ABC Installer.exe`
3. Immediate crash (log is attached)

## Your Environment
Node v8.11.3
NPM 5.6.0
Yarn 1.7.0
Electron 2.0.0
Windows 10, 64bit

My iohook config
```
  "iohook": {
    "targets": [
      "node-57",
      "electron-57"
    ],
    "platforms": [
      "win32"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
```
[iohook-crash.log](https://github.com/WilixLead/iohook/files/2143450/iohook-crash.log)

**Comment by anhang** [comment]
Looks like it's SegfaultHandler. Commenting out the SegfaultHandler initialization in index.js fixed this for me.

**Comment by Djiit** [comment]
Hi there,

it's not the first problem we have with SegfaultHandler. Does anybody wants to play around with it, maybe bumping versions and/or trying to completely remove it ?

Thanks !

**Comment by Djiit** [comment]
Hi @anhang, could you retry with segfault-handler v1.0.1 ?

**Comment by Djiit** [comment]
Could you try with v0.3.0 ?

**Comment by anhang** [comment]
This is now working fine. thanks!
