### ISSUE TITLE
Intermittent cursor freezing on mousemove on 2018 macbook pro (High Sierra 10.13.6)

### ISSUE THREAD

**Issue by natew** [wilix-team/iohook#96]
## Expected Behavior

No freeze

## Current Behavior

Just got a new macbook and my whole system would freeze after about 45 minutes of running my node app using iohook. Think I finally narrowed in on this issue (after a journey to find that it was in fact the node app freezing things.. thought it was maybe a bad migration or something).

Oddly what I noticed was that it would only freeze when moving my mouse. If I stopped using the mouse I could keep working. Otherwise everything would basically lock up. After killing the node app it seemed to be fine.

Running the same (cloned) hard drive on my old macbook pro doesn't have this issue.

I did try cleaning and re-installing node modules.

## Possible Solution

🤷‍♂️ 

## Your Environment

* Version used: 0.2.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Tried Node 9, 10
* Operating System and version (desktop or mobile): Tried High Sierra and then Mojave in desperation

**Comment by xudaolong** [comment]
@natew same problem with you since I update macos version 10.13.6.

**Comment by vhmth** [comment]
Also potentially hitting this, and there's no way we can reliably restart the Electron procs since we do video recording in our application (that would disturb recording state/lead to corruption).

Doesn't seem like there's much in those forums on how to fix this unfortunately. :-\

**Comment by natew** [comment]
@xudaolong that temporary hack may help until the main package is fixed.

@vhmth presumably you can just kill the iohook sub-process (not sure if the snippet does that) or you could run iohook in a sub-process and kill it.

**Comment by Djiit** [comment]
Hi guys, 

Sorry I can't really help you here without the right macbook. Maybe @WilixLead can help ?

**Comment by wurikiji** [comment]
Same problem. I can't apply @xudaolong 's solution because my app should not be restarted.
I will apply @natew 's solution (separate iohook sub-process).

**Comment by renjfk** [comment]
Tested by copying latest changes from [libuiohook](https://github.com/kwhat/libuiohook) and it seems to be resolved my issue on 10.14 (18A391).

**Comment by iameli** [comment]
Encountered this yesterday on Mojave — attempting  @xudaolong's workaround first. @renjfk are those changes reflected in your fork here? https://github.com/renjfk/iohook

**Comment by renjfk** [comment]
Nope I haven't pushed changes, what I did was simply overwriting existing source from [libuiohook](https://github.com/kwhat/libuiohook) on local copy although you might lose some functionalities since I believe repo has some local commits to support extra stuff.

**Comment by renjfk** [comment]
Nope I haven't pushed changes, what I did was simply overwriting existing source from [libuiohook](https://github.com/kwhat/libuiohook) on local copy although you might lose some functionalities since I believe repo has some local commits to support extra stuff.

**Comment by Djiit** [comment]
I'm working on this in #106. Just backported the modifications about click propagation. Tests are pending.
