### ISSUE TITLE
Ctrl + Alt + X

### ISSUE THREAD

**Issue by entozoon** [wilix-team/iohook#97]
Attempting to have a global shortcut for ctrl+alt+x

## Expected Behavior
Hit ctrl+alt+x and get a console log

## Current Behavior
Nothin'

I have tried, in vain:
```
ioHook.registerShortcut([29, 56, 120], keys => {
  console.log("ctrl+alt+x");
});
```

Which is odd because, ctrl+alt+f7 works with:
```
ioHook.registerShortcut([29, 56, 65], keys => {
  console.log("ctrl+alt+f7");
});
```

Picking up any old keypress, happily understands ctrl-x and alt-x, but not _both_ ctrlKey and altKey being true
```
ioHook.on("keypress", event => {
  console.log(event);
```

## Your Environment
Windows 10

**Comment by entozoon** [comment]
SOLUTION:
```ioHook.registerShortcut([29, 56, 45], keys => { ```

`45` being `x`.
I've absolutely no idea why it is a different code to those shown by `.on("keypress", event => { ...`  - I just happened to try one posted [here](https://github.com/WilixLead/iohook/issues/74#issuecomment-387387810).

This could all be cleared up by solving issue https://github.com/WilixLead/iohook/issues/74

**Comment by Djiit** [comment]
Hi there!

Thanks for your feedback. Indeed we could fix many thing with this issue.

I'm tagging this issue and leaving it open for now.

**Comment by Djiit** [comment]
Closing for #74
